<?php
# !! WARNING ! WARNING ! WARNING ! WARNING ! WARNING ! WARNING !!
# !!                                                           !!
# !!   This file is autogenerated by generate.php              !!
# !!                                                           !!
# !!   DO NOT change it.  ALL changes will be lost after you   !!
# !!   regenerate it again.                                    !!
# !!                                                           !!
# !! WARNING ! WARNING ! WARNING ! WARNING ! WARNING ! WARNING !!
/**
 * Support data classes for the Simple Registration Extension.
 */
/**
 * Raw list of all Time Zones.
 *
 * @see OpenID_SR_TimeZone
 * @see OpenID_SR_Country
 * @package OpenID.SR.data
 */
class OpenID_SR_data_AutoGeneratedTimeZone
{
    /**
     * Country Code to Country Time Zones mapping.
     *
     * This Hash is keyed by the Two Letter Country Code, and each
     * element is a Array with all the Time Zones that exist in the
     * respective country.  Each Time Zone is a Hash with a single
     * key 'TZ' with the Time Zone code.
     *
     * Example:
     *
     * <code>
     * $data = array(
     *     'AQ' => array(
     *         array('TZ' => 'Antarctica/McMurdo'),
     *         array('TZ' => 'Antarctica/South_Pole'),
     *     ),
     * );
     * </code>
     *
     * @var hash
     */
    static $data = array (
  'AD' => 
  array (
    0 => 
    array (
      'TZ' => 'Europe/Andorra',
    ),
  ),
  'AE' => 
  array (
    0 => 
    array (
      'TZ' => 'Asia/Dubai',
    ),
  ),
  'AF' => 
  array (
    0 => 
    array (
      'TZ' => 'Asia/Kabul',
    ),
  ),
  'AG' => 
  array (
    0 => 
    array (
      'TZ' => 'America/Antigua',
    ),
  ),
  'AI' => 
  array (
    0 => 
    array (
      'TZ' => 'America/Anguilla',
    ),
  ),
  'AL' => 
  array (
    0 => 
    array (
      'TZ' => 'Europe/Tirane',
    ),
  ),
  'AM' => 
  array (
    0 => 
    array (
      'TZ' => 'Asia/Yerevan',
    ),
  ),
  'AN' => 
  array (
    0 => 
    array (
      'TZ' => 'America/Curacao',
    ),
  ),
  'AO' => 
  array (
    0 => 
    array (
      'TZ' => 'Africa/Luanda',
    ),
  ),
  'AQ' => 
  array (
    0 => 
    array (
      'TZ' => 'Antarctica/McMurdo',
    ),
    1 => 
    array (
      'TZ' => 'Antarctica/South_Pole',
    ),
    2 => 
    array (
      'TZ' => 'Antarctica/Rothera',
    ),
    3 => 
    array (
      'TZ' => 'Antarctica/Palmer',
    ),
    4 => 
    array (
      'TZ' => 'Antarctica/Mawson',
    ),
    5 => 
    array (
      'TZ' => 'Antarctica/Davis',
    ),
    6 => 
    array (
      'TZ' => 'Antarctica/Casey',
    ),
    7 => 
    array (
      'TZ' => 'Antarctica/Vostok',
    ),
    8 => 
    array (
      'TZ' => 'Antarctica/DumontDUrville',
    ),
    9 => 
    array (
      'TZ' => 'Antarctica/Syowa',
    ),
  ),
  'AR' => 
  array (
    0 => 
    array (
      'TZ' => 'America/Argentina/Buenos_Aires',
    ),
    1 => 
    array (
      'TZ' => 'America/Argentina/Cordoba',
    ),
    2 => 
    array (
      'TZ' => 'America/Argentina/Jujuy',
    ),
    3 => 
    array (
      'TZ' => 'America/Argentina/Tucuman',
    ),
    4 => 
    array (
      'TZ' => 'America/Argentina/Catamarca',
    ),
    5 => 
    array (
      'TZ' => 'America/Argentina/La_Rioja',
    ),
    6 => 
    array (
      'TZ' => 'America/Argentina/San_Juan',
    ),
    7 => 
    array (
      'TZ' => 'America/Argentina/Mendoza',
    ),
    8 => 
    array (
      'TZ' => 'America/Argentina/Rio_Gallegos',
    ),
    9 => 
    array (
      'TZ' => 'America/Argentina/Ushuaia',
    ),
  ),
  'AS' => 
  array (
    0 => 
    array (
      'TZ' => 'Pacific/Pago_Pago',
    ),
  ),
  'AT' => 
  array (
    0 => 
    array (
      'TZ' => 'Europe/Vienna',
    ),
  ),
  'AU' => 
  array (
    0 => 
    array (
      'TZ' => 'Australia/Lord_Howe',
    ),
    1 => 
    array (
      'TZ' => 'Australia/Hobart',
    ),
    2 => 
    array (
      'TZ' => 'Australia/Currie',
    ),
    3 => 
    array (
      'TZ' => 'Australia/Melbourne',
    ),
    4 => 
    array (
      'TZ' => 'Australia/Sydney',
    ),
    5 => 
    array (
      'TZ' => 'Australia/Broken_Hill',
    ),
    6 => 
    array (
      'TZ' => 'Australia/Brisbane',
    ),
    7 => 
    array (
      'TZ' => 'Australia/Lindeman',
    ),
    8 => 
    array (
      'TZ' => 'Australia/Adelaide',
    ),
    9 => 
    array (
      'TZ' => 'Australia/Darwin',
    ),
    10 => 
    array (
      'TZ' => 'Australia/Perth',
    ),
    11 => 
    array (
      'TZ' => 'Australia/Eucla',
    ),
  ),
  'AW' => 
  array (
    0 => 
    array (
      'TZ' => 'America/Aruba',
    ),
  ),
  'AX' => 
  array (
    0 => 
    array (
      'TZ' => 'Europe/Mariehamn',
    ),
  ),
  'AZ' => 
  array (
    0 => 
    array (
      'TZ' => 'Asia/Baku',
    ),
  ),
  'BA' => 
  array (
    0 => 
    array (
      'TZ' => 'Europe/Sarajevo',
    ),
  ),
  'BB' => 
  array (
    0 => 
    array (
      'TZ' => 'America/Barbados',
    ),
  ),
  'BD' => 
  array (
    0 => 
    array (
      'TZ' => 'Asia/Dhaka',
    ),
  ),
  'BE' => 
  array (
    0 => 
    array (
      'TZ' => 'Europe/Brussels',
    ),
  ),
  'BF' => 
  array (
    0 => 
    array (
      'TZ' => 'Africa/Ouagadougou',
    ),
  ),
  'BG' => 
  array (
    0 => 
    array (
      'TZ' => 'Europe/Sofia',
    ),
  ),
  'BH' => 
  array (
    0 => 
    array (
      'TZ' => 'Asia/Bahrain',
    ),
  ),
  'BI' => 
  array (
    0 => 
    array (
      'TZ' => 'Africa/Bujumbura',
    ),
  ),
  'BJ' => 
  array (
    0 => 
    array (
      'TZ' => 'Africa/Porto-Novo',
    ),
  ),
  'BM' => 
  array (
    0 => 
    array (
      'TZ' => 'Atlantic/Bermuda',
    ),
  ),
  'BN' => 
  array (
    0 => 
    array (
      'TZ' => 'Asia/Brunei',
    ),
  ),
  'BO' => 
  array (
    0 => 
    array (
      'TZ' => 'America/La_Paz',
    ),
  ),
  'BR' => 
  array (
    0 => 
    array (
      'TZ' => 'America/Noronha',
    ),
    1 => 
    array (
      'TZ' => 'America/Belem',
    ),
    2 => 
    array (
      'TZ' => 'America/Fortaleza',
    ),
    3 => 
    array (
      'TZ' => 'America/Recife',
    ),
    4 => 
    array (
      'TZ' => 'America/Araguaina',
    ),
    5 => 
    array (
      'TZ' => 'America/Maceio',
    ),
    6 => 
    array (
      'TZ' => 'America/Bahia',
    ),
    7 => 
    array (
      'TZ' => 'America/Sao_Paulo',
    ),
    8 => 
    array (
      'TZ' => 'America/Campo_Grande',
    ),
    9 => 
    array (
      'TZ' => 'America/Cuiaba',
    ),
    10 => 
    array (
      'TZ' => 'America/Porto_Velho',
    ),
    11 => 
    array (
      'TZ' => 'America/Boa_Vista',
    ),
    12 => 
    array (
      'TZ' => 'America/Manaus',
    ),
    13 => 
    array (
      'TZ' => 'America/Eirunepe',
    ),
    14 => 
    array (
      'TZ' => 'America/Rio_Branco',
    ),
  ),
  'BS' => 
  array (
    0 => 
    array (
      'TZ' => 'America/Nassau',
    ),
  ),
  'BT' => 
  array (
    0 => 
    array (
      'TZ' => 'Asia/Thimphu',
    ),
  ),
  'BW' => 
  array (
    0 => 
    array (
      'TZ' => 'Africa/Gaborone',
    ),
  ),
  'BY' => 
  array (
    0 => 
    array (
      'TZ' => 'Europe/Minsk',
    ),
  ),
  'BZ' => 
  array (
    0 => 
    array (
      'TZ' => 'America/Belize',
    ),
  ),
  'CA' => 
  array (
    0 => 
    array (
      'TZ' => 'America/St_Johns',
    ),
    1 => 
    array (
      'TZ' => 'America/Halifax',
    ),
    2 => 
    array (
      'TZ' => 'America/Glace_Bay',
    ),
    3 => 
    array (
      'TZ' => 'America/Moncton',
    ),
    4 => 
    array (
      'TZ' => 'America/Goose_Bay',
    ),
    5 => 
    array (
      'TZ' => 'America/Blanc-Sablon',
    ),
    6 => 
    array (
      'TZ' => 'America/Montreal',
    ),
    7 => 
    array (
      'TZ' => 'America/Toronto',
    ),
    8 => 
    array (
      'TZ' => 'America/Nipigon',
    ),
    9 => 
    array (
      'TZ' => 'America/Thunder_Bay',
    ),
    10 => 
    array (
      'TZ' => 'America/Iqaluit',
    ),
    11 => 
    array (
      'TZ' => 'America/Pangnirtung',
    ),
    12 => 
    array (
      'TZ' => 'America/Resolute',
    ),
    13 => 
    array (
      'TZ' => 'America/Atikokan',
    ),
    14 => 
    array (
      'TZ' => 'America/Rankin_Inlet',
    ),
    15 => 
    array (
      'TZ' => 'America/Winnipeg',
    ),
    16 => 
    array (
      'TZ' => 'America/Rainy_River',
    ),
    17 => 
    array (
      'TZ' => 'America/Cambridge_Bay',
    ),
    18 => 
    array (
      'TZ' => 'America/Regina',
    ),
    19 => 
    array (
      'TZ' => 'America/Swift_Current',
    ),
    20 => 
    array (
      'TZ' => 'America/Edmonton',
    ),
    21 => 
    array (
      'TZ' => 'America/Yellowknife',
    ),
    22 => 
    array (
      'TZ' => 'America/Inuvik',
    ),
    23 => 
    array (
      'TZ' => 'America/Dawson_Creek',
    ),
    24 => 
    array (
      'TZ' => 'America/Vancouver',
    ),
    25 => 
    array (
      'TZ' => 'America/Whitehorse',
    ),
    26 => 
    array (
      'TZ' => 'America/Dawson',
    ),
  ),
  'CC' => 
  array (
    0 => 
    array (
      'TZ' => 'Indian/Cocos',
    ),
  ),
  'CD' => 
  array (
    0 => 
    array (
      'TZ' => 'Africa/Kinshasa',
    ),
    1 => 
    array (
      'TZ' => 'Africa/Lubumbashi',
    ),
  ),
  'CF' => 
  array (
    0 => 
    array (
      'TZ' => 'Africa/Bangui',
    ),
  ),
  'CG' => 
  array (
    0 => 
    array (
      'TZ' => 'Africa/Brazzaville',
    ),
  ),
  'CH' => 
  array (
    0 => 
    array (
      'TZ' => 'Europe/Zurich',
    ),
  ),
  'CI' => 
  array (
    0 => 
    array (
      'TZ' => 'Africa/Abidjan',
    ),
  ),
  'CK' => 
  array (
    0 => 
    array (
      'TZ' => 'Pacific/Rarotonga',
    ),
  ),
  'CL' => 
  array (
    0 => 
    array (
      'TZ' => 'America/Santiago',
    ),
    1 => 
    array (
      'TZ' => 'Pacific/Easter',
    ),
  ),
  'CM' => 
  array (
    0 => 
    array (
      'TZ' => 'Africa/Douala',
    ),
  ),
  'CN' => 
  array (
    0 => 
    array (
      'TZ' => 'Asia/Shanghai',
    ),
    1 => 
    array (
      'TZ' => 'Asia/Harbin',
    ),
    2 => 
    array (
      'TZ' => 'Asia/Chongqing',
    ),
    3 => 
    array (
      'TZ' => 'Asia/Urumqi',
    ),
    4 => 
    array (
      'TZ' => 'Asia/Kashgar',
    ),
  ),
  'CO' => 
  array (
    0 => 
    array (
      'TZ' => 'America/Bogota',
    ),
  ),
  'CR' => 
  array (
    0 => 
    array (
      'TZ' => 'America/Costa_Rica',
    ),
  ),
  'CU' => 
  array (
    0 => 
    array (
      'TZ' => 'America/Havana',
    ),
  ),
  'CV' => 
  array (
    0 => 
    array (
      'TZ' => 'Atlantic/Cape_Verde',
    ),
  ),
  'CX' => 
  array (
    0 => 
    array (
      'TZ' => 'Indian/Christmas',
    ),
  ),
  'CY' => 
  array (
    0 => 
    array (
      'TZ' => 'Asia/Nicosia',
    ),
  ),
  'CZ' => 
  array (
    0 => 
    array (
      'TZ' => 'Europe/Prague',
    ),
  ),
  'DE' => 
  array (
    0 => 
    array (
      'TZ' => 'Europe/Berlin',
    ),
  ),
  'DJ' => 
  array (
    0 => 
    array (
      'TZ' => 'Africa/Djibouti',
    ),
  ),
  'DK' => 
  array (
    0 => 
    array (
      'TZ' => 'Europe/Copenhagen',
    ),
  ),
  'DM' => 
  array (
    0 => 
    array (
      'TZ' => 'America/Dominica',
    ),
  ),
  'DO' => 
  array (
    0 => 
    array (
      'TZ' => 'America/Santo_Domingo',
    ),
  ),
  'DZ' => 
  array (
    0 => 
    array (
      'TZ' => 'Africa/Algiers',
    ),
  ),
  'EC' => 
  array (
    0 => 
    array (
      'TZ' => 'America/Guayaquil',
    ),
    1 => 
    array (
      'TZ' => 'Pacific/Galapagos',
    ),
  ),
  'EE' => 
  array (
    0 => 
    array (
      'TZ' => 'Europe/Tallinn',
    ),
  ),
  'EG' => 
  array (
    0 => 
    array (
      'TZ' => 'Africa/Cairo',
    ),
  ),
  'EH' => 
  array (
    0 => 
    array (
      'TZ' => 'Africa/El_Aaiun',
    ),
  ),
  'ER' => 
  array (
    0 => 
    array (
      'TZ' => 'Africa/Asmara',
    ),
  ),
  'ES' => 
  array (
    0 => 
    array (
      'TZ' => 'Europe/Madrid',
    ),
    1 => 
    array (
      'TZ' => 'Africa/Ceuta',
    ),
    2 => 
    array (
      'TZ' => 'Atlantic/Canary',
    ),
  ),
  'ET' => 
  array (
    0 => 
    array (
      'TZ' => 'Africa/Addis_Ababa',
    ),
  ),
  'FI' => 
  array (
    0 => 
    array (
      'TZ' => 'Europe/Helsinki',
    ),
  ),
  'FJ' => 
  array (
    0 => 
    array (
      'TZ' => 'Pacific/Fiji',
    ),
  ),
  'FK' => 
  array (
    0 => 
    array (
      'TZ' => 'Atlantic/Stanley',
    ),
  ),
  'FM' => 
  array (
    0 => 
    array (
      'TZ' => 'Pacific/Truk',
    ),
    1 => 
    array (
      'TZ' => 'Pacific/Ponape',
    ),
    2 => 
    array (
      'TZ' => 'Pacific/Kosrae',
    ),
  ),
  'FO' => 
  array (
    0 => 
    array (
      'TZ' => 'Atlantic/Faroe',
    ),
  ),
  'FR' => 
  array (
    0 => 
    array (
      'TZ' => 'Europe/Paris',
    ),
  ),
  'GA' => 
  array (
    0 => 
    array (
      'TZ' => 'Africa/Libreville',
    ),
  ),
  'GB' => 
  array (
    0 => 
    array (
      'TZ' => 'Europe/London',
    ),
  ),
  'GD' => 
  array (
    0 => 
    array (
      'TZ' => 'America/Grenada',
    ),
  ),
  'GE' => 
  array (
    0 => 
    array (
      'TZ' => 'Asia/Tbilisi',
    ),
  ),
  'GF' => 
  array (
    0 => 
    array (
      'TZ' => 'America/Cayenne',
    ),
  ),
  'GG' => 
  array (
    0 => 
    array (
      'TZ' => 'Europe/Guernsey',
    ),
  ),
  'GH' => 
  array (
    0 => 
    array (
      'TZ' => 'Africa/Accra',
    ),
  ),
  'GI' => 
  array (
    0 => 
    array (
      'TZ' => 'Europe/Gibraltar',
    ),
  ),
  'GL' => 
  array (
    0 => 
    array (
      'TZ' => 'America/Godthab',
    ),
    1 => 
    array (
      'TZ' => 'America/Danmarkshavn',
    ),
    2 => 
    array (
      'TZ' => 'America/Scoresbysund',
    ),
    3 => 
    array (
      'TZ' => 'America/Thule',
    ),
  ),
  'GM' => 
  array (
    0 => 
    array (
      'TZ' => 'Africa/Banjul',
    ),
  ),
  'GN' => 
  array (
    0 => 
    array (
      'TZ' => 'Africa/Conakry',
    ),
  ),
  'GP' => 
  array (
    0 => 
    array (
      'TZ' => 'America/Guadeloupe',
    ),
  ),
  'GQ' => 
  array (
    0 => 
    array (
      'TZ' => 'Africa/Malabo',
    ),
  ),
  'GR' => 
  array (
    0 => 
    array (
      'TZ' => 'Europe/Athens',
    ),
  ),
  'GS' => 
  array (
    0 => 
    array (
      'TZ' => 'Atlantic/South_Georgia',
    ),
  ),
  'GT' => 
  array (
    0 => 
    array (
      'TZ' => 'America/Guatemala',
    ),
  ),
  'GU' => 
  array (
    0 => 
    array (
      'TZ' => 'Pacific/Guam',
    ),
  ),
  'GW' => 
  array (
    0 => 
    array (
      'TZ' => 'Africa/Bissau',
    ),
  ),
  'GY' => 
  array (
    0 => 
    array (
      'TZ' => 'America/Guyana',
    ),
  ),
  'HK' => 
  array (
    0 => 
    array (
      'TZ' => 'Asia/Hong_Kong',
    ),
  ),
  'HN' => 
  array (
    0 => 
    array (
      'TZ' => 'America/Tegucigalpa',
    ),
  ),
  'HR' => 
  array (
    0 => 
    array (
      'TZ' => 'Europe/Zagreb',
    ),
  ),
  'HT' => 
  array (
    0 => 
    array (
      'TZ' => 'America/Port-au-Prince',
    ),
  ),
  'HU' => 
  array (
    0 => 
    array (
      'TZ' => 'Europe/Budapest',
    ),
  ),
  'ID' => 
  array (
    0 => 
    array (
      'TZ' => 'Asia/Jakarta',
    ),
    1 => 
    array (
      'TZ' => 'Asia/Pontianak',
    ),
    2 => 
    array (
      'TZ' => 'Asia/Makassar',
    ),
    3 => 
    array (
      'TZ' => 'Asia/Jayapura',
    ),
  ),
  'IE' => 
  array (
    0 => 
    array (
      'TZ' => 'Europe/Dublin',
    ),
  ),
  'IL' => 
  array (
    0 => 
    array (
      'TZ' => 'Asia/Jerusalem',
    ),
  ),
  'IM' => 
  array (
    0 => 
    array (
      'TZ' => 'Europe/Isle_of_Man',
    ),
  ),
  'IN' => 
  array (
    0 => 
    array (
      'TZ' => 'Asia/Calcutta',
    ),
  ),
  'IO' => 
  array (
    0 => 
    array (
      'TZ' => 'Indian/Chagos',
    ),
  ),
  'IQ' => 
  array (
    0 => 
    array (
      'TZ' => 'Asia/Baghdad',
    ),
  ),
  'IR' => 
  array (
    0 => 
    array (
      'TZ' => 'Asia/Tehran',
    ),
  ),
  'IS' => 
  array (
    0 => 
    array (
      'TZ' => 'Atlantic/Reykjavik',
    ),
  ),
  'IT' => 
  array (
    0 => 
    array (
      'TZ' => 'Europe/Rome',
    ),
  ),
  'JE' => 
  array (
    0 => 
    array (
      'TZ' => 'Europe/Jersey',
    ),
  ),
  'JM' => 
  array (
    0 => 
    array (
      'TZ' => 'America/Jamaica',
    ),
  ),
  'JO' => 
  array (
    0 => 
    array (
      'TZ' => 'Asia/Amman',
    ),
  ),
  'JP' => 
  array (
    0 => 
    array (
      'TZ' => 'Asia/Tokyo',
    ),
  ),
  'KE' => 
  array (
    0 => 
    array (
      'TZ' => 'Africa/Nairobi',
    ),
  ),
  'KG' => 
  array (
    0 => 
    array (
      'TZ' => 'Asia/Bishkek',
    ),
  ),
  'KH' => 
  array (
    0 => 
    array (
      'TZ' => 'Asia/Phnom_Penh',
    ),
  ),
  'KI' => 
  array (
    0 => 
    array (
      'TZ' => 'Pacific/Tarawa',
    ),
    1 => 
    array (
      'TZ' => 'Pacific/Enderbury',
    ),
    2 => 
    array (
      'TZ' => 'Pacific/Kiritimati',
    ),
  ),
  'KM' => 
  array (
    0 => 
    array (
      'TZ' => 'Indian/Comoro',
    ),
  ),
  'KN' => 
  array (
    0 => 
    array (
      'TZ' => 'America/St_Kitts',
    ),
  ),
  'KP' => 
  array (
    0 => 
    array (
      'TZ' => 'Asia/Pyongyang',
    ),
  ),
  'KR' => 
  array (
    0 => 
    array (
      'TZ' => 'Asia/Seoul',
    ),
  ),
  'KW' => 
  array (
    0 => 
    array (
      'TZ' => 'Asia/Kuwait',
    ),
  ),
  'KY' => 
  array (
    0 => 
    array (
      'TZ' => 'America/Cayman',
    ),
  ),
  'KZ' => 
  array (
    0 => 
    array (
      'TZ' => 'Asia/Almaty',
    ),
    1 => 
    array (
      'TZ' => 'Asia/Qyzylorda',
    ),
    2 => 
    array (
      'TZ' => 'Asia/Aqtobe',
    ),
    3 => 
    array (
      'TZ' => 'Asia/Aqtau',
    ),
    4 => 
    array (
      'TZ' => 'Asia/Oral',
    ),
  ),
  'LA' => 
  array (
    0 => 
    array (
      'TZ' => 'Asia/Vientiane',
    ),
  ),
  'LB' => 
  array (
    0 => 
    array (
      'TZ' => 'Asia/Beirut',
    ),
  ),
  'LC' => 
  array (
    0 => 
    array (
      'TZ' => 'America/St_Lucia',
    ),
  ),
  'LI' => 
  array (
    0 => 
    array (
      'TZ' => 'Europe/Vaduz',
    ),
  ),
  'LK' => 
  array (
    0 => 
    array (
      'TZ' => 'Asia/Colombo',
    ),
  ),
  'LR' => 
  array (
    0 => 
    array (
      'TZ' => 'Africa/Monrovia',
    ),
  ),
  'LS' => 
  array (
    0 => 
    array (
      'TZ' => 'Africa/Maseru',
    ),
  ),
  'LT' => 
  array (
    0 => 
    array (
      'TZ' => 'Europe/Vilnius',
    ),
  ),
  'LU' => 
  array (
    0 => 
    array (
      'TZ' => 'Europe/Luxembourg',
    ),
  ),
  'LV' => 
  array (
    0 => 
    array (
      'TZ' => 'Europe/Riga',
    ),
  ),
  'LY' => 
  array (
    0 => 
    array (
      'TZ' => 'Africa/Tripoli',
    ),
  ),
  'MA' => 
  array (
    0 => 
    array (
      'TZ' => 'Africa/Casablanca',
    ),
  ),
  'MC' => 
  array (
    0 => 
    array (
      'TZ' => 'Europe/Monaco',
    ),
  ),
  'MD' => 
  array (
    0 => 
    array (
      'TZ' => 'Europe/Chisinau',
    ),
  ),
  'ME' => 
  array (
    0 => 
    array (
      'TZ' => 'Europe/Podgorica',
    ),
  ),
  'MG' => 
  array (
    0 => 
    array (
      'TZ' => 'Indian/Antananarivo',
    ),
  ),
  'MH' => 
  array (
    0 => 
    array (
      'TZ' => 'Pacific/Majuro',
    ),
    1 => 
    array (
      'TZ' => 'Pacific/Kwajalein',
    ),
  ),
  'MK' => 
  array (
    0 => 
    array (
      'TZ' => 'Europe/Skopje',
    ),
  ),
  'ML' => 
  array (
    0 => 
    array (
      'TZ' => 'Africa/Bamako',
    ),
  ),
  'MM' => 
  array (
    0 => 
    array (
      'TZ' => 'Asia/Rangoon',
    ),
  ),
  'MN' => 
  array (
    0 => 
    array (
      'TZ' => 'Asia/Ulaanbaatar',
    ),
    1 => 
    array (
      'TZ' => 'Asia/Hovd',
    ),
    2 => 
    array (
      'TZ' => 'Asia/Choibalsan',
    ),
  ),
  'MO' => 
  array (
    0 => 
    array (
      'TZ' => 'Asia/Macau',
    ),
  ),
  'MP' => 
  array (
    0 => 
    array (
      'TZ' => 'Pacific/Saipan',
    ),
  ),
  'MQ' => 
  array (
    0 => 
    array (
      'TZ' => 'America/Martinique',
    ),
  ),
  'MR' => 
  array (
    0 => 
    array (
      'TZ' => 'Africa/Nouakchott',
    ),
  ),
  'MS' => 
  array (
    0 => 
    array (
      'TZ' => 'America/Montserrat',
    ),
  ),
  'MT' => 
  array (
    0 => 
    array (
      'TZ' => 'Europe/Malta',
    ),
  ),
  'MU' => 
  array (
    0 => 
    array (
      'TZ' => 'Indian/Mauritius',
    ),
  ),
  'MV' => 
  array (
    0 => 
    array (
      'TZ' => 'Indian/Maldives',
    ),
  ),
  'MW' => 
  array (
    0 => 
    array (
      'TZ' => 'Africa/Blantyre',
    ),
  ),
  'MX' => 
  array (
    0 => 
    array (
      'TZ' => 'America/Mexico_City',
    ),
    1 => 
    array (
      'TZ' => 'America/Cancun',
    ),
    2 => 
    array (
      'TZ' => 'America/Merida',
    ),
    3 => 
    array (
      'TZ' => 'America/Monterrey',
    ),
    4 => 
    array (
      'TZ' => 'America/Mazatlan',
    ),
    5 => 
    array (
      'TZ' => 'America/Chihuahua',
    ),
    6 => 
    array (
      'TZ' => 'America/Hermosillo',
    ),
    7 => 
    array (
      'TZ' => 'America/Tijuana',
    ),
  ),
  'MY' => 
  array (
    0 => 
    array (
      'TZ' => 'Asia/Kuala_Lumpur',
    ),
    1 => 
    array (
      'TZ' => 'Asia/Kuching',
    ),
  ),
  'MZ' => 
  array (
    0 => 
    array (
      'TZ' => 'Africa/Maputo',
    ),
  ),
  'NA' => 
  array (
    0 => 
    array (
      'TZ' => 'Africa/Windhoek',
    ),
  ),
  'NC' => 
  array (
    0 => 
    array (
      'TZ' => 'Pacific/Noumea',
    ),
  ),
  'NE' => 
  array (
    0 => 
    array (
      'TZ' => 'Africa/Niamey',
    ),
  ),
  'NF' => 
  array (
    0 => 
    array (
      'TZ' => 'Pacific/Norfolk',
    ),
  ),
  'NG' => 
  array (
    0 => 
    array (
      'TZ' => 'Africa/Lagos',
    ),
  ),
  'NI' => 
  array (
    0 => 
    array (
      'TZ' => 'America/Managua',
    ),
  ),
  'NL' => 
  array (
    0 => 
    array (
      'TZ' => 'Europe/Amsterdam',
    ),
  ),
  'NO' => 
  array (
    0 => 
    array (
      'TZ' => 'Europe/Oslo',
    ),
  ),
  'NP' => 
  array (
    0 => 
    array (
      'TZ' => 'Asia/Katmandu',
    ),
  ),
  'NR' => 
  array (
    0 => 
    array (
      'TZ' => 'Pacific/Nauru',
    ),
  ),
  'NU' => 
  array (
    0 => 
    array (
      'TZ' => 'Pacific/Niue',
    ),
  ),
  'NZ' => 
  array (
    0 => 
    array (
      'TZ' => 'Pacific/Auckland',
    ),
    1 => 
    array (
      'TZ' => 'Pacific/Chatham',
    ),
  ),
  'OM' => 
  array (
    0 => 
    array (
      'TZ' => 'Asia/Muscat',
    ),
  ),
  'PA' => 
  array (
    0 => 
    array (
      'TZ' => 'America/Panama',
    ),
  ),
  'PE' => 
  array (
    0 => 
    array (
      'TZ' => 'America/Lima',
    ),
  ),
  'PF' => 
  array (
    0 => 
    array (
      'TZ' => 'Pacific/Tahiti',
    ),
    1 => 
    array (
      'TZ' => 'Pacific/Marquesas',
    ),
    2 => 
    array (
      'TZ' => 'Pacific/Gambier',
    ),
  ),
  'PG' => 
  array (
    0 => 
    array (
      'TZ' => 'Pacific/Port_Moresby',
    ),
  ),
  'PH' => 
  array (
    0 => 
    array (
      'TZ' => 'Asia/Manila',
    ),
  ),
  'PK' => 
  array (
    0 => 
    array (
      'TZ' => 'Asia/Karachi',
    ),
  ),
  'PL' => 
  array (
    0 => 
    array (
      'TZ' => 'Europe/Warsaw',
    ),
  ),
  'PM' => 
  array (
    0 => 
    array (
      'TZ' => 'America/Miquelon',
    ),
  ),
  'PN' => 
  array (
    0 => 
    array (
      'TZ' => 'Pacific/Pitcairn',
    ),
  ),
  'PR' => 
  array (
    0 => 
    array (
      'TZ' => 'America/Puerto_Rico',
    ),
  ),
  'PS' => 
  array (
    0 => 
    array (
      'TZ' => 'Asia/Gaza',
    ),
  ),
  'PT' => 
  array (
    0 => 
    array (
      'TZ' => 'Europe/Lisbon',
    ),
    1 => 
    array (
      'TZ' => 'Atlantic/Madeira',
    ),
    2 => 
    array (
      'TZ' => 'Atlantic/Azores',
    ),
  ),
  'PW' => 
  array (
    0 => 
    array (
      'TZ' => 'Pacific/Palau',
    ),
  ),
  'PY' => 
  array (
    0 => 
    array (
      'TZ' => 'America/Asuncion',
    ),
  ),
  'QA' => 
  array (
    0 => 
    array (
      'TZ' => 'Asia/Qatar',
    ),
  ),
  'RE' => 
  array (
    0 => 
    array (
      'TZ' => 'Indian/Reunion',
    ),
  ),
  'RO' => 
  array (
    0 => 
    array (
      'TZ' => 'Europe/Bucharest',
    ),
  ),
  'RS' => 
  array (
    0 => 
    array (
      'TZ' => 'Europe/Belgrade',
    ),
  ),
  'RU' => 
  array (
    0 => 
    array (
      'TZ' => 'Europe/Kaliningrad',
    ),
    1 => 
    array (
      'TZ' => 'Europe/Moscow',
    ),
    2 => 
    array (
      'TZ' => 'Europe/Volgograd',
    ),
    3 => 
    array (
      'TZ' => 'Europe/Samara',
    ),
    4 => 
    array (
      'TZ' => 'Asia/Yekaterinburg',
    ),
    5 => 
    array (
      'TZ' => 'Asia/Omsk',
    ),
    6 => 
    array (
      'TZ' => 'Asia/Novosibirsk',
    ),
    7 => 
    array (
      'TZ' => 'Asia/Krasnoyarsk',
    ),
    8 => 
    array (
      'TZ' => 'Asia/Irkutsk',
    ),
    9 => 
    array (
      'TZ' => 'Asia/Yakutsk',
    ),
    10 => 
    array (
      'TZ' => 'Asia/Vladivostok',
    ),
    11 => 
    array (
      'TZ' => 'Asia/Sakhalin',
    ),
    12 => 
    array (
      'TZ' => 'Asia/Magadan',
    ),
    13 => 
    array (
      'TZ' => 'Asia/Kamchatka',
    ),
    14 => 
    array (
      'TZ' => 'Asia/Anadyr',
    ),
  ),
  'RW' => 
  array (
    0 => 
    array (
      'TZ' => 'Africa/Kigali',
    ),
  ),
  'SA' => 
  array (
    0 => 
    array (
      'TZ' => 'Asia/Riyadh',
    ),
  ),
  'SB' => 
  array (
    0 => 
    array (
      'TZ' => 'Pacific/Guadalcanal',
    ),
  ),
  'SC' => 
  array (
    0 => 
    array (
      'TZ' => 'Indian/Mahe',
    ),
  ),
  'SD' => 
  array (
    0 => 
    array (
      'TZ' => 'Africa/Khartoum',
    ),
  ),
  'SE' => 
  array (
    0 => 
    array (
      'TZ' => 'Europe/Stockholm',
    ),
  ),
  'SG' => 
  array (
    0 => 
    array (
      'TZ' => 'Asia/Singapore',
    ),
  ),
  'SH' => 
  array (
    0 => 
    array (
      'TZ' => 'Atlantic/St_Helena',
    ),
  ),
  'SI' => 
  array (
    0 => 
    array (
      'TZ' => 'Europe/Ljubljana',
    ),
  ),
  'SJ' => 
  array (
    0 => 
    array (
      'TZ' => 'Arctic/Longyearbyen',
    ),
    1 => 
    array (
      'TZ' => 'Atlantic/Jan_Mayen',
    ),
  ),
  'SK' => 
  array (
    0 => 
    array (
      'TZ' => 'Europe/Bratislava',
    ),
  ),
  'SL' => 
  array (
    0 => 
    array (
      'TZ' => 'Africa/Freetown',
    ),
  ),
  'SM' => 
  array (
    0 => 
    array (
      'TZ' => 'Europe/San_Marino',
    ),
  ),
  'SN' => 
  array (
    0 => 
    array (
      'TZ' => 'Africa/Dakar',
    ),
  ),
  'SO' => 
  array (
    0 => 
    array (
      'TZ' => 'Africa/Mogadishu',
    ),
  ),
  'SR' => 
  array (
    0 => 
    array (
      'TZ' => 'America/Paramaribo',
    ),
  ),
  'ST' => 
  array (
    0 => 
    array (
      'TZ' => 'Africa/Sao_Tome',
    ),
  ),
  'SV' => 
  array (
    0 => 
    array (
      'TZ' => 'America/El_Salvador',
    ),
  ),
  'SY' => 
  array (
    0 => 
    array (
      'TZ' => 'Asia/Damascus',
    ),
  ),
  'SZ' => 
  array (
    0 => 
    array (
      'TZ' => 'Africa/Mbabane',
    ),
  ),
  'TC' => 
  array (
    0 => 
    array (
      'TZ' => 'America/Grand_Turk',
    ),
  ),
  'TD' => 
  array (
    0 => 
    array (
      'TZ' => 'Africa/Ndjamena',
    ),
  ),
  'TF' => 
  array (
    0 => 
    array (
      'TZ' => 'Indian/Kerguelen',
    ),
  ),
  'TG' => 
  array (
    0 => 
    array (
      'TZ' => 'Africa/Lome',
    ),
  ),
  'TH' => 
  array (
    0 => 
    array (
      'TZ' => 'Asia/Bangkok',
    ),
  ),
  'TJ' => 
  array (
    0 => 
    array (
      'TZ' => 'Asia/Dushanbe',
    ),
  ),
  'TK' => 
  array (
    0 => 
    array (
      'TZ' => 'Pacific/Fakaofo',
    ),
  ),
  'TL' => 
  array (
    0 => 
    array (
      'TZ' => 'Asia/Dili',
    ),
  ),
  'TM' => 
  array (
    0 => 
    array (
      'TZ' => 'Asia/Ashgabat',
    ),
  ),
  'TN' => 
  array (
    0 => 
    array (
      'TZ' => 'Africa/Tunis',
    ),
  ),
  'TO' => 
  array (
    0 => 
    array (
      'TZ' => 'Pacific/Tongatapu',
    ),
  ),
  'TR' => 
  array (
    0 => 
    array (
      'TZ' => 'Europe/Istanbul',
    ),
  ),
  'TT' => 
  array (
    0 => 
    array (
      'TZ' => 'America/Port_of_Spain',
    ),
  ),
  'TV' => 
  array (
    0 => 
    array (
      'TZ' => 'Pacific/Funafuti',
    ),
  ),
  'TW' => 
  array (
    0 => 
    array (
      'TZ' => 'Asia/Taipei',
    ),
  ),
  'TZ' => 
  array (
    0 => 
    array (
      'TZ' => 'Africa/Dar_es_Salaam',
    ),
  ),
  'UA' => 
  array (
    0 => 
    array (
      'TZ' => 'Europe/Kiev',
    ),
    1 => 
    array (
      'TZ' => 'Europe/Uzhgorod',
    ),
    2 => 
    array (
      'TZ' => 'Europe/Zaporozhye',
    ),
    3 => 
    array (
      'TZ' => 'Europe/Simferopol',
    ),
  ),
  'UG' => 
  array (
    0 => 
    array (
      'TZ' => 'Africa/Kampala',
    ),
  ),
  'UM' => 
  array (
    0 => 
    array (
      'TZ' => 'Pacific/Johnston',
    ),
    1 => 
    array (
      'TZ' => 'Pacific/Midway',
    ),
    2 => 
    array (
      'TZ' => 'Pacific/Wake',
    ),
  ),
  'US' => 
  array (
    0 => 
    array (
      'TZ' => 'America/New_York',
    ),
    1 => 
    array (
      'TZ' => 'America/Detroit',
    ),
    2 => 
    array (
      'TZ' => 'America/Kentucky/Louisville',
    ),
    3 => 
    array (
      'TZ' => 'America/Kentucky/Monticello',
    ),
    4 => 
    array (
      'TZ' => 'America/Indiana/Indianapolis',
    ),
    5 => 
    array (
      'TZ' => 'America/Indiana/Knox',
    ),
    6 => 
    array (
      'TZ' => 'America/Indiana/Winamac',
    ),
    7 => 
    array (
      'TZ' => 'America/Indiana/Marengo',
    ),
    8 => 
    array (
      'TZ' => 'America/Indiana/Vevay',
    ),
    9 => 
    array (
      'TZ' => 'America/Chicago',
    ),
    10 => 
    array (
      'TZ' => 'America/Indiana/Vincennes',
    ),
    11 => 
    array (
      'TZ' => 'America/Indiana/Petersburg',
    ),
    12 => 
    array (
      'TZ' => 'America/Menominee',
    ),
    13 => 
    array (
      'TZ' => 'America/North_Dakota/Center',
    ),
    14 => 
    array (
      'TZ' => 'America/North_Dakota/New_Salem',
    ),
    15 => 
    array (
      'TZ' => 'America/Denver',
    ),
    16 => 
    array (
      'TZ' => 'America/Boise',
    ),
    17 => 
    array (
      'TZ' => 'America/Shiprock',
    ),
    18 => 
    array (
      'TZ' => 'America/Phoenix',
    ),
    19 => 
    array (
      'TZ' => 'America/Los_Angeles',
    ),
    20 => 
    array (
      'TZ' => 'America/Anchorage',
    ),
    21 => 
    array (
      'TZ' => 'America/Juneau',
    ),
    22 => 
    array (
      'TZ' => 'America/Yakutat',
    ),
    23 => 
    array (
      'TZ' => 'America/Nome',
    ),
    24 => 
    array (
      'TZ' => 'America/Adak',
    ),
    25 => 
    array (
      'TZ' => 'Pacific/Honolulu',
    ),
  ),
  'UY' => 
  array (
    0 => 
    array (
      'TZ' => 'America/Montevideo',
    ),
  ),
  'UZ' => 
  array (
    0 => 
    array (
      'TZ' => 'Asia/Samarkand',
    ),
    1 => 
    array (
      'TZ' => 'Asia/Tashkent',
    ),
  ),
  'VA' => 
  array (
    0 => 
    array (
      'TZ' => 'Europe/Vatican',
    ),
  ),
  'VC' => 
  array (
    0 => 
    array (
      'TZ' => 'America/St_Vincent',
    ),
  ),
  'VE' => 
  array (
    0 => 
    array (
      'TZ' => 'America/Caracas',
    ),
  ),
  'VG' => 
  array (
    0 => 
    array (
      'TZ' => 'America/Tortola',
    ),
  ),
  'VI' => 
  array (
    0 => 
    array (
      'TZ' => 'America/St_Thomas',
    ),
  ),
  'VN' => 
  array (
    0 => 
    array (
      'TZ' => 'Asia/Saigon',
    ),
  ),
  'VU' => 
  array (
    0 => 
    array (
      'TZ' => 'Pacific/Efate',
    ),
  ),
  'WF' => 
  array (
    0 => 
    array (
      'TZ' => 'Pacific/Wallis',
    ),
  ),
  'WS' => 
  array (
    0 => 
    array (
      'TZ' => 'Pacific/Apia',
    ),
  ),
  'YE' => 
  array (
    0 => 
    array (
      'TZ' => 'Asia/Aden',
    ),
  ),
  'YT' => 
  array (
    0 => 
    array (
      'TZ' => 'Indian/Mayotte',
    ),
  ),
  'ZA' => 
  array (
    0 => 
    array (
      'TZ' => 'Africa/Johannesburg',
    ),
  ),
  'ZM' => 
  array (
    0 => 
    array (
      'TZ' => 'Africa/Lusaka',
    ),
  ),
  'ZW' => 
  array (
    0 => 
    array (
      'TZ' => 'Africa/Harare',
    ),
  ),
);

    # 
    /**
     * Zone Code to Country Codes mapping.
     *
     * This Hash is keyed by the Time Zone code, and each element is a
     * Array with all the Countries that have the respective Time Zone.
     *
     * Example:
     *
     * <code>
     * $data = array(
     *     'Antarctica/McMurdo' => array('AQ'),
     * );
     * </code>
     *
     * @var hash
     */
    static $zoneToCountry = array (
  'Europe/Andorra' => 
  array (
    0 => 'AD',
  ),
  'Asia/Dubai' => 
  array (
    0 => 'AE',
  ),
  'Asia/Kabul' => 
  array (
    0 => 'AF',
  ),
  'America/Antigua' => 
  array (
    0 => 'AG',
  ),
  'America/Anguilla' => 
  array (
    0 => 'AI',
  ),
  'Europe/Tirane' => 
  array (
    0 => 'AL',
  ),
  'Asia/Yerevan' => 
  array (
    0 => 'AM',
  ),
  'America/Curacao' => 
  array (
    0 => 'AN',
  ),
  'Africa/Luanda' => 
  array (
    0 => 'AO',
  ),
  'Antarctica/McMurdo' => 
  array (
    0 => 'AQ',
  ),
  'Antarctica/South_Pole' => 
  array (
    0 => 'AQ',
  ),
  'Antarctica/Rothera' => 
  array (
    0 => 'AQ',
  ),
  'Antarctica/Palmer' => 
  array (
    0 => 'AQ',
  ),
  'Antarctica/Mawson' => 
  array (
    0 => 'AQ',
  ),
  'Antarctica/Davis' => 
  array (
    0 => 'AQ',
  ),
  'Antarctica/Casey' => 
  array (
    0 => 'AQ',
  ),
  'Antarctica/Vostok' => 
  array (
    0 => 'AQ',
  ),
  'Antarctica/DumontDUrville' => 
  array (
    0 => 'AQ',
  ),
  'Antarctica/Syowa' => 
  array (
    0 => 'AQ',
  ),
  'America/Argentina/Buenos_Aires' => 
  array (
    0 => 'AR',
  ),
  'America/Argentina/Cordoba' => 
  array (
    0 => 'AR',
  ),
  'America/Argentina/Jujuy' => 
  array (
    0 => 'AR',
  ),
  'America/Argentina/Tucuman' => 
  array (
    0 => 'AR',
  ),
  'America/Argentina/Catamarca' => 
  array (
    0 => 'AR',
  ),
  'America/Argentina/La_Rioja' => 
  array (
    0 => 'AR',
  ),
  'America/Argentina/San_Juan' => 
  array (
    0 => 'AR',
  ),
  'America/Argentina/Mendoza' => 
  array (
    0 => 'AR',
  ),
  'America/Argentina/Rio_Gallegos' => 
  array (
    0 => 'AR',
  ),
  'America/Argentina/Ushuaia' => 
  array (
    0 => 'AR',
  ),
  'Pacific/Pago_Pago' => 
  array (
    0 => 'AS',
  ),
  'Europe/Vienna' => 
  array (
    0 => 'AT',
  ),
  'Australia/Lord_Howe' => 
  array (
    0 => 'AU',
  ),
  'Australia/Hobart' => 
  array (
    0 => 'AU',
  ),
  'Australia/Currie' => 
  array (
    0 => 'AU',
  ),
  'Australia/Melbourne' => 
  array (
    0 => 'AU',
  ),
  'Australia/Sydney' => 
  array (
    0 => 'AU',
  ),
  'Australia/Broken_Hill' => 
  array (
    0 => 'AU',
  ),
  'Australia/Brisbane' => 
  array (
    0 => 'AU',
  ),
  'Australia/Lindeman' => 
  array (
    0 => 'AU',
  ),
  'Australia/Adelaide' => 
  array (
    0 => 'AU',
  ),
  'Australia/Darwin' => 
  array (
    0 => 'AU',
  ),
  'Australia/Perth' => 
  array (
    0 => 'AU',
  ),
  'Australia/Eucla' => 
  array (
    0 => 'AU',
  ),
  'America/Aruba' => 
  array (
    0 => 'AW',
  ),
  'Europe/Mariehamn' => 
  array (
    0 => 'AX',
  ),
  'Asia/Baku' => 
  array (
    0 => 'AZ',
  ),
  'Europe/Sarajevo' => 
  array (
    0 => 'BA',
  ),
  'America/Barbados' => 
  array (
    0 => 'BB',
  ),
  'Asia/Dhaka' => 
  array (
    0 => 'BD',
  ),
  'Europe/Brussels' => 
  array (
    0 => 'BE',
  ),
  'Africa/Ouagadougou' => 
  array (
    0 => 'BF',
  ),
  'Europe/Sofia' => 
  array (
    0 => 'BG',
  ),
  'Asia/Bahrain' => 
  array (
    0 => 'BH',
  ),
  'Africa/Bujumbura' => 
  array (
    0 => 'BI',
  ),
  'Africa/Porto-Novo' => 
  array (
    0 => 'BJ',
  ),
  'Atlantic/Bermuda' => 
  array (
    0 => 'BM',
  ),
  'Asia/Brunei' => 
  array (
    0 => 'BN',
  ),
  'America/La_Paz' => 
  array (
    0 => 'BO',
  ),
  'America/Noronha' => 
  array (
    0 => 'BR',
  ),
  'America/Belem' => 
  array (
    0 => 'BR',
  ),
  'America/Fortaleza' => 
  array (
    0 => 'BR',
  ),
  'America/Recife' => 
  array (
    0 => 'BR',
  ),
  'America/Araguaina' => 
  array (
    0 => 'BR',
  ),
  'America/Maceio' => 
  array (
    0 => 'BR',
  ),
  'America/Bahia' => 
  array (
    0 => 'BR',
  ),
  'America/Sao_Paulo' => 
  array (
    0 => 'BR',
  ),
  'America/Campo_Grande' => 
  array (
    0 => 'BR',
  ),
  'America/Cuiaba' => 
  array (
    0 => 'BR',
  ),
  'America/Porto_Velho' => 
  array (
    0 => 'BR',
  ),
  'America/Boa_Vista' => 
  array (
    0 => 'BR',
  ),
  'America/Manaus' => 
  array (
    0 => 'BR',
  ),
  'America/Eirunepe' => 
  array (
    0 => 'BR',
  ),
  'America/Rio_Branco' => 
  array (
    0 => 'BR',
  ),
  'America/Nassau' => 
  array (
    0 => 'BS',
  ),
  'Asia/Thimphu' => 
  array (
    0 => 'BT',
  ),
  'Africa/Gaborone' => 
  array (
    0 => 'BW',
  ),
  'Europe/Minsk' => 
  array (
    0 => 'BY',
  ),
  'America/Belize' => 
  array (
    0 => 'BZ',
  ),
  'America/St_Johns' => 
  array (
    0 => 'CA',
  ),
  'America/Halifax' => 
  array (
    0 => 'CA',
  ),
  'America/Glace_Bay' => 
  array (
    0 => 'CA',
  ),
  'America/Moncton' => 
  array (
    0 => 'CA',
  ),
  'America/Goose_Bay' => 
  array (
    0 => 'CA',
  ),
  'America/Blanc-Sablon' => 
  array (
    0 => 'CA',
  ),
  'America/Montreal' => 
  array (
    0 => 'CA',
  ),
  'America/Toronto' => 
  array (
    0 => 'CA',
  ),
  'America/Nipigon' => 
  array (
    0 => 'CA',
  ),
  'America/Thunder_Bay' => 
  array (
    0 => 'CA',
  ),
  'America/Iqaluit' => 
  array (
    0 => 'CA',
  ),
  'America/Pangnirtung' => 
  array (
    0 => 'CA',
  ),
  'America/Resolute' => 
  array (
    0 => 'CA',
  ),
  'America/Atikokan' => 
  array (
    0 => 'CA',
  ),
  'America/Rankin_Inlet' => 
  array (
    0 => 'CA',
  ),
  'America/Winnipeg' => 
  array (
    0 => 'CA',
  ),
  'America/Rainy_River' => 
  array (
    0 => 'CA',
  ),
  'America/Cambridge_Bay' => 
  array (
    0 => 'CA',
  ),
  'America/Regina' => 
  array (
    0 => 'CA',
  ),
  'America/Swift_Current' => 
  array (
    0 => 'CA',
  ),
  'America/Edmonton' => 
  array (
    0 => 'CA',
  ),
  'America/Yellowknife' => 
  array (
    0 => 'CA',
  ),
  'America/Inuvik' => 
  array (
    0 => 'CA',
  ),
  'America/Dawson_Creek' => 
  array (
    0 => 'CA',
  ),
  'America/Vancouver' => 
  array (
    0 => 'CA',
  ),
  'America/Whitehorse' => 
  array (
    0 => 'CA',
  ),
  'America/Dawson' => 
  array (
    0 => 'CA',
  ),
  'Indian/Cocos' => 
  array (
    0 => 'CC',
  ),
  'Africa/Kinshasa' => 
  array (
    0 => 'CD',
  ),
  'Africa/Lubumbashi' => 
  array (
    0 => 'CD',
  ),
  'Africa/Bangui' => 
  array (
    0 => 'CF',
  ),
  'Africa/Brazzaville' => 
  array (
    0 => 'CG',
  ),
  'Europe/Zurich' => 
  array (
    0 => 'CH',
  ),
  'Africa/Abidjan' => 
  array (
    0 => 'CI',
  ),
  'Pacific/Rarotonga' => 
  array (
    0 => 'CK',
  ),
  'America/Santiago' => 
  array (
    0 => 'CL',
  ),
  'Pacific/Easter' => 
  array (
    0 => 'CL',
  ),
  'Africa/Douala' => 
  array (
    0 => 'CM',
  ),
  'Asia/Shanghai' => 
  array (
    0 => 'CN',
  ),
  'Asia/Harbin' => 
  array (
    0 => 'CN',
  ),
  'Asia/Chongqing' => 
  array (
    0 => 'CN',
  ),
  'Asia/Urumqi' => 
  array (
    0 => 'CN',
  ),
  'Asia/Kashgar' => 
  array (
    0 => 'CN',
  ),
  'America/Bogota' => 
  array (
    0 => 'CO',
  ),
  'America/Costa_Rica' => 
  array (
    0 => 'CR',
  ),
  'America/Havana' => 
  array (
    0 => 'CU',
  ),
  'Atlantic/Cape_Verde' => 
  array (
    0 => 'CV',
  ),
  'Indian/Christmas' => 
  array (
    0 => 'CX',
  ),
  'Asia/Nicosia' => 
  array (
    0 => 'CY',
  ),
  'Europe/Prague' => 
  array (
    0 => 'CZ',
  ),
  'Europe/Berlin' => 
  array (
    0 => 'DE',
  ),
  'Africa/Djibouti' => 
  array (
    0 => 'DJ',
  ),
  'Europe/Copenhagen' => 
  array (
    0 => 'DK',
  ),
  'America/Dominica' => 
  array (
    0 => 'DM',
  ),
  'America/Santo_Domingo' => 
  array (
    0 => 'DO',
  ),
  'Africa/Algiers' => 
  array (
    0 => 'DZ',
  ),
  'America/Guayaquil' => 
  array (
    0 => 'EC',
  ),
  'Pacific/Galapagos' => 
  array (
    0 => 'EC',
  ),
  'Europe/Tallinn' => 
  array (
    0 => 'EE',
  ),
  'Africa/Cairo' => 
  array (
    0 => 'EG',
  ),
  'Africa/El_Aaiun' => 
  array (
    0 => 'EH',
  ),
  'Africa/Asmara' => 
  array (
    0 => 'ER',
  ),
  'Europe/Madrid' => 
  array (
    0 => 'ES',
  ),
  'Africa/Ceuta' => 
  array (
    0 => 'ES',
  ),
  'Atlantic/Canary' => 
  array (
    0 => 'ES',
  ),
  'Africa/Addis_Ababa' => 
  array (
    0 => 'ET',
  ),
  'Europe/Helsinki' => 
  array (
    0 => 'FI',
  ),
  'Pacific/Fiji' => 
  array (
    0 => 'FJ',
  ),
  'Atlantic/Stanley' => 
  array (
    0 => 'FK',
  ),
  'Pacific/Truk' => 
  array (
    0 => 'FM',
  ),
  'Pacific/Ponape' => 
  array (
    0 => 'FM',
  ),
  'Pacific/Kosrae' => 
  array (
    0 => 'FM',
  ),
  'Atlantic/Faroe' => 
  array (
    0 => 'FO',
  ),
  'Europe/Paris' => 
  array (
    0 => 'FR',
  ),
  'Africa/Libreville' => 
  array (
    0 => 'GA',
  ),
  'Europe/London' => 
  array (
    0 => 'GB',
  ),
  'America/Grenada' => 
  array (
    0 => 'GD',
  ),
  'Asia/Tbilisi' => 
  array (
    0 => 'GE',
  ),
  'America/Cayenne' => 
  array (
    0 => 'GF',
  ),
  'Europe/Guernsey' => 
  array (
    0 => 'GG',
  ),
  'Africa/Accra' => 
  array (
    0 => 'GH',
  ),
  'Europe/Gibraltar' => 
  array (
    0 => 'GI',
  ),
  'America/Godthab' => 
  array (
    0 => 'GL',
  ),
  'America/Danmarkshavn' => 
  array (
    0 => 'GL',
  ),
  'America/Scoresbysund' => 
  array (
    0 => 'GL',
  ),
  'America/Thule' => 
  array (
    0 => 'GL',
  ),
  'Africa/Banjul' => 
  array (
    0 => 'GM',
  ),
  'Africa/Conakry' => 
  array (
    0 => 'GN',
  ),
  'America/Guadeloupe' => 
  array (
    0 => 'GP',
  ),
  'Africa/Malabo' => 
  array (
    0 => 'GQ',
  ),
  'Europe/Athens' => 
  array (
    0 => 'GR',
  ),
  'Atlantic/South_Georgia' => 
  array (
    0 => 'GS',
  ),
  'America/Guatemala' => 
  array (
    0 => 'GT',
  ),
  'Pacific/Guam' => 
  array (
    0 => 'GU',
  ),
  'Africa/Bissau' => 
  array (
    0 => 'GW',
  ),
  'America/Guyana' => 
  array (
    0 => 'GY',
  ),
  'Asia/Hong_Kong' => 
  array (
    0 => 'HK',
  ),
  'America/Tegucigalpa' => 
  array (
    0 => 'HN',
  ),
  'Europe/Zagreb' => 
  array (
    0 => 'HR',
  ),
  'America/Port-au-Prince' => 
  array (
    0 => 'HT',
  ),
  'Europe/Budapest' => 
  array (
    0 => 'HU',
  ),
  'Asia/Jakarta' => 
  array (
    0 => 'ID',
  ),
  'Asia/Pontianak' => 
  array (
    0 => 'ID',
  ),
  'Asia/Makassar' => 
  array (
    0 => 'ID',
  ),
  'Asia/Jayapura' => 
  array (
    0 => 'ID',
  ),
  'Europe/Dublin' => 
  array (
    0 => 'IE',
  ),
  'Asia/Jerusalem' => 
  array (
    0 => 'IL',
  ),
  'Europe/Isle_of_Man' => 
  array (
    0 => 'IM',
  ),
  'Asia/Calcutta' => 
  array (
    0 => 'IN',
  ),
  'Indian/Chagos' => 
  array (
    0 => 'IO',
  ),
  'Asia/Baghdad' => 
  array (
    0 => 'IQ',
  ),
  'Asia/Tehran' => 
  array (
    0 => 'IR',
  ),
  'Atlantic/Reykjavik' => 
  array (
    0 => 'IS',
  ),
  'Europe/Rome' => 
  array (
    0 => 'IT',
  ),
  'Europe/Jersey' => 
  array (
    0 => 'JE',
  ),
  'America/Jamaica' => 
  array (
    0 => 'JM',
  ),
  'Asia/Amman' => 
  array (
    0 => 'JO',
  ),
  'Asia/Tokyo' => 
  array (
    0 => 'JP',
  ),
  'Africa/Nairobi' => 
  array (
    0 => 'KE',
  ),
  'Asia/Bishkek' => 
  array (
    0 => 'KG',
  ),
  'Asia/Phnom_Penh' => 
  array (
    0 => 'KH',
  ),
  'Pacific/Tarawa' => 
  array (
    0 => 'KI',
  ),
  'Pacific/Enderbury' => 
  array (
    0 => 'KI',
  ),
  'Pacific/Kiritimati' => 
  array (
    0 => 'KI',
  ),
  'Indian/Comoro' => 
  array (
    0 => 'KM',
  ),
  'America/St_Kitts' => 
  array (
    0 => 'KN',
  ),
  'Asia/Pyongyang' => 
  array (
    0 => 'KP',
  ),
  'Asia/Seoul' => 
  array (
    0 => 'KR',
  ),
  'Asia/Kuwait' => 
  array (
    0 => 'KW',
  ),
  'America/Cayman' => 
  array (
    0 => 'KY',
  ),
  'Asia/Almaty' => 
  array (
    0 => 'KZ',
  ),
  'Asia/Qyzylorda' => 
  array (
    0 => 'KZ',
  ),
  'Asia/Aqtobe' => 
  array (
    0 => 'KZ',
  ),
  'Asia/Aqtau' => 
  array (
    0 => 'KZ',
  ),
  'Asia/Oral' => 
  array (
    0 => 'KZ',
  ),
  'Asia/Vientiane' => 
  array (
    0 => 'LA',
  ),
  'Asia/Beirut' => 
  array (
    0 => 'LB',
  ),
  'America/St_Lucia' => 
  array (
    0 => 'LC',
  ),
  'Europe/Vaduz' => 
  array (
    0 => 'LI',
  ),
  'Asia/Colombo' => 
  array (
    0 => 'LK',
  ),
  'Africa/Monrovia' => 
  array (
    0 => 'LR',
  ),
  'Africa/Maseru' => 
  array (
    0 => 'LS',
  ),
  'Europe/Vilnius' => 
  array (
    0 => 'LT',
  ),
  'Europe/Luxembourg' => 
  array (
    0 => 'LU',
  ),
  'Europe/Riga' => 
  array (
    0 => 'LV',
  ),
  'Africa/Tripoli' => 
  array (
    0 => 'LY',
  ),
  'Africa/Casablanca' => 
  array (
    0 => 'MA',
  ),
  'Europe/Monaco' => 
  array (
    0 => 'MC',
  ),
  'Europe/Chisinau' => 
  array (
    0 => 'MD',
  ),
  'Europe/Podgorica' => 
  array (
    0 => 'ME',
  ),
  'Indian/Antananarivo' => 
  array (
    0 => 'MG',
  ),
  'Pacific/Majuro' => 
  array (
    0 => 'MH',
  ),
  'Pacific/Kwajalein' => 
  array (
    0 => 'MH',
  ),
  'Europe/Skopje' => 
  array (
    0 => 'MK',
  ),
  'Africa/Bamako' => 
  array (
    0 => 'ML',
  ),
  'Asia/Rangoon' => 
  array (
    0 => 'MM',
  ),
  'Asia/Ulaanbaatar' => 
  array (
    0 => 'MN',
  ),
  'Asia/Hovd' => 
  array (
    0 => 'MN',
  ),
  'Asia/Choibalsan' => 
  array (
    0 => 'MN',
  ),
  'Asia/Macau' => 
  array (
    0 => 'MO',
  ),
  'Pacific/Saipan' => 
  array (
    0 => 'MP',
  ),
  'America/Martinique' => 
  array (
    0 => 'MQ',
  ),
  'Africa/Nouakchott' => 
  array (
    0 => 'MR',
  ),
  'America/Montserrat' => 
  array (
    0 => 'MS',
  ),
  'Europe/Malta' => 
  array (
    0 => 'MT',
  ),
  'Indian/Mauritius' => 
  array (
    0 => 'MU',
  ),
  'Indian/Maldives' => 
  array (
    0 => 'MV',
  ),
  'Africa/Blantyre' => 
  array (
    0 => 'MW',
  ),
  'America/Mexico_City' => 
  array (
    0 => 'MX',
  ),
  'America/Cancun' => 
  array (
    0 => 'MX',
  ),
  'America/Merida' => 
  array (
    0 => 'MX',
  ),
  'America/Monterrey' => 
  array (
    0 => 'MX',
  ),
  'America/Mazatlan' => 
  array (
    0 => 'MX',
  ),
  'America/Chihuahua' => 
  array (
    0 => 'MX',
  ),
  'America/Hermosillo' => 
  array (
    0 => 'MX',
  ),
  'America/Tijuana' => 
  array (
    0 => 'MX',
  ),
  'Asia/Kuala_Lumpur' => 
  array (
    0 => 'MY',
  ),
  'Asia/Kuching' => 
  array (
    0 => 'MY',
  ),
  'Africa/Maputo' => 
  array (
    0 => 'MZ',
  ),
  'Africa/Windhoek' => 
  array (
    0 => 'NA',
  ),
  'Pacific/Noumea' => 
  array (
    0 => 'NC',
  ),
  'Africa/Niamey' => 
  array (
    0 => 'NE',
  ),
  'Pacific/Norfolk' => 
  array (
    0 => 'NF',
  ),
  'Africa/Lagos' => 
  array (
    0 => 'NG',
  ),
  'America/Managua' => 
  array (
    0 => 'NI',
  ),
  'Europe/Amsterdam' => 
  array (
    0 => 'NL',
  ),
  'Europe/Oslo' => 
  array (
    0 => 'NO',
  ),
  'Asia/Katmandu' => 
  array (
    0 => 'NP',
  ),
  'Pacific/Nauru' => 
  array (
    0 => 'NR',
  ),
  'Pacific/Niue' => 
  array (
    0 => 'NU',
  ),
  'Pacific/Auckland' => 
  array (
    0 => 'NZ',
  ),
  'Pacific/Chatham' => 
  array (
    0 => 'NZ',
  ),
  'Asia/Muscat' => 
  array (
    0 => 'OM',
  ),
  'America/Panama' => 
  array (
    0 => 'PA',
  ),
  'America/Lima' => 
  array (
    0 => 'PE',
  ),
  'Pacific/Tahiti' => 
  array (
    0 => 'PF',
  ),
  'Pacific/Marquesas' => 
  array (
    0 => 'PF',
  ),
  'Pacific/Gambier' => 
  array (
    0 => 'PF',
  ),
  'Pacific/Port_Moresby' => 
  array (
    0 => 'PG',
  ),
  'Asia/Manila' => 
  array (
    0 => 'PH',
  ),
  'Asia/Karachi' => 
  array (
    0 => 'PK',
  ),
  'Europe/Warsaw' => 
  array (
    0 => 'PL',
  ),
  'America/Miquelon' => 
  array (
    0 => 'PM',
  ),
  'Pacific/Pitcairn' => 
  array (
    0 => 'PN',
  ),
  'America/Puerto_Rico' => 
  array (
    0 => 'PR',
  ),
  'Asia/Gaza' => 
  array (
    0 => 'PS',
  ),
  'Europe/Lisbon' => 
  array (
    0 => 'PT',
  ),
  'Atlantic/Madeira' => 
  array (
    0 => 'PT',
  ),
  'Atlantic/Azores' => 
  array (
    0 => 'PT',
  ),
  'Pacific/Palau' => 
  array (
    0 => 'PW',
  ),
  'America/Asuncion' => 
  array (
    0 => 'PY',
  ),
  'Asia/Qatar' => 
  array (
    0 => 'QA',
  ),
  'Indian/Reunion' => 
  array (
    0 => 'RE',
  ),
  'Europe/Bucharest' => 
  array (
    0 => 'RO',
  ),
  'Europe/Belgrade' => 
  array (
    0 => 'RS',
  ),
  'Europe/Kaliningrad' => 
  array (
    0 => 'RU',
  ),
  'Europe/Moscow' => 
  array (
    0 => 'RU',
  ),
  'Europe/Volgograd' => 
  array (
    0 => 'RU',
  ),
  'Europe/Samara' => 
  array (
    0 => 'RU',
  ),
  'Asia/Yekaterinburg' => 
  array (
    0 => 'RU',
  ),
  'Asia/Omsk' => 
  array (
    0 => 'RU',
  ),
  'Asia/Novosibirsk' => 
  array (
    0 => 'RU',
  ),
  'Asia/Krasnoyarsk' => 
  array (
    0 => 'RU',
  ),
  'Asia/Irkutsk' => 
  array (
    0 => 'RU',
  ),
  'Asia/Yakutsk' => 
  array (
    0 => 'RU',
  ),
  'Asia/Vladivostok' => 
  array (
    0 => 'RU',
  ),
  'Asia/Sakhalin' => 
  array (
    0 => 'RU',
  ),
  'Asia/Magadan' => 
  array (
    0 => 'RU',
  ),
  'Asia/Kamchatka' => 
  array (
    0 => 'RU',
  ),
  'Asia/Anadyr' => 
  array (
    0 => 'RU',
  ),
  'Africa/Kigali' => 
  array (
    0 => 'RW',
  ),
  'Asia/Riyadh' => 
  array (
    0 => 'SA',
  ),
  'Pacific/Guadalcanal' => 
  array (
    0 => 'SB',
  ),
  'Indian/Mahe' => 
  array (
    0 => 'SC',
  ),
  'Africa/Khartoum' => 
  array (
    0 => 'SD',
  ),
  'Europe/Stockholm' => 
  array (
    0 => 'SE',
  ),
  'Asia/Singapore' => 
  array (
    0 => 'SG',
  ),
  'Atlantic/St_Helena' => 
  array (
    0 => 'SH',
  ),
  'Europe/Ljubljana' => 
  array (
    0 => 'SI',
  ),
  'Arctic/Longyearbyen' => 
  array (
    0 => 'SJ',
  ),
  'Atlantic/Jan_Mayen' => 
  array (
    0 => 'SJ',
  ),
  'Europe/Bratislava' => 
  array (
    0 => 'SK',
  ),
  'Africa/Freetown' => 
  array (
    0 => 'SL',
  ),
  'Europe/San_Marino' => 
  array (
    0 => 'SM',
  ),
  'Africa/Dakar' => 
  array (
    0 => 'SN',
  ),
  'Africa/Mogadishu' => 
  array (
    0 => 'SO',
  ),
  'America/Paramaribo' => 
  array (
    0 => 'SR',
  ),
  'Africa/Sao_Tome' => 
  array (
    0 => 'ST',
  ),
  'America/El_Salvador' => 
  array (
    0 => 'SV',
  ),
  'Asia/Damascus' => 
  array (
    0 => 'SY',
  ),
  'Africa/Mbabane' => 
  array (
    0 => 'SZ',
  ),
  'America/Grand_Turk' => 
  array (
    0 => 'TC',
  ),
  'Africa/Ndjamena' => 
  array (
    0 => 'TD',
  ),
  'Indian/Kerguelen' => 
  array (
    0 => 'TF',
  ),
  'Africa/Lome' => 
  array (
    0 => 'TG',
  ),
  'Asia/Bangkok' => 
  array (
    0 => 'TH',
  ),
  'Asia/Dushanbe' => 
  array (
    0 => 'TJ',
  ),
  'Pacific/Fakaofo' => 
  array (
    0 => 'TK',
  ),
  'Asia/Dili' => 
  array (
    0 => 'TL',
  ),
  'Asia/Ashgabat' => 
  array (
    0 => 'TM',
  ),
  'Africa/Tunis' => 
  array (
    0 => 'TN',
  ),
  'Pacific/Tongatapu' => 
  array (
    0 => 'TO',
  ),
  'Europe/Istanbul' => 
  array (
    0 => 'TR',
  ),
  'America/Port_of_Spain' => 
  array (
    0 => 'TT',
  ),
  'Pacific/Funafuti' => 
  array (
    0 => 'TV',
  ),
  'Asia/Taipei' => 
  array (
    0 => 'TW',
  ),
  'Africa/Dar_es_Salaam' => 
  array (
    0 => 'TZ',
  ),
  'Europe/Kiev' => 
  array (
    0 => 'UA',
  ),
  'Europe/Uzhgorod' => 
  array (
    0 => 'UA',
  ),
  'Europe/Zaporozhye' => 
  array (
    0 => 'UA',
  ),
  'Europe/Simferopol' => 
  array (
    0 => 'UA',
  ),
  'Africa/Kampala' => 
  array (
    0 => 'UG',
  ),
  'Pacific/Johnston' => 
  array (
    0 => 'UM',
  ),
  'Pacific/Midway' => 
  array (
    0 => 'UM',
  ),
  'Pacific/Wake' => 
  array (
    0 => 'UM',
  ),
  'America/New_York' => 
  array (
    0 => 'US',
  ),
  'America/Detroit' => 
  array (
    0 => 'US',
  ),
  'America/Kentucky/Louisville' => 
  array (
    0 => 'US',
  ),
  'America/Kentucky/Monticello' => 
  array (
    0 => 'US',
  ),
  'America/Indiana/Indianapolis' => 
  array (
    0 => 'US',
  ),
  'America/Indiana/Knox' => 
  array (
    0 => 'US',
  ),
  'America/Indiana/Winamac' => 
  array (
    0 => 'US',
  ),
  'America/Indiana/Marengo' => 
  array (
    0 => 'US',
  ),
  'America/Indiana/Vevay' => 
  array (
    0 => 'US',
  ),
  'America/Chicago' => 
  array (
    0 => 'US',
  ),
  'America/Indiana/Vincennes' => 
  array (
    0 => 'US',
  ),
  'America/Indiana/Petersburg' => 
  array (
    0 => 'US',
  ),
  'America/Menominee' => 
  array (
    0 => 'US',
  ),
  'America/North_Dakota/Center' => 
  array (
    0 => 'US',
  ),
  'America/North_Dakota/New_Salem' => 
  array (
    0 => 'US',
  ),
  'America/Denver' => 
  array (
    0 => 'US',
  ),
  'America/Boise' => 
  array (
    0 => 'US',
  ),
  'America/Shiprock' => 
  array (
    0 => 'US',
  ),
  'America/Phoenix' => 
  array (
    0 => 'US',
  ),
  'America/Los_Angeles' => 
  array (
    0 => 'US',
  ),
  'America/Anchorage' => 
  array (
    0 => 'US',
  ),
  'America/Juneau' => 
  array (
    0 => 'US',
  ),
  'America/Yakutat' => 
  array (
    0 => 'US',
  ),
  'America/Nome' => 
  array (
    0 => 'US',
  ),
  'America/Adak' => 
  array (
    0 => 'US',
  ),
  'Pacific/Honolulu' => 
  array (
    0 => 'US',
  ),
  'America/Montevideo' => 
  array (
    0 => 'UY',
  ),
  'Asia/Samarkand' => 
  array (
    0 => 'UZ',
  ),
  'Asia/Tashkent' => 
  array (
    0 => 'UZ',
  ),
  'Europe/Vatican' => 
  array (
    0 => 'VA',
  ),
  'America/St_Vincent' => 
  array (
    0 => 'VC',
  ),
  'America/Caracas' => 
  array (
    0 => 'VE',
  ),
  'America/Tortola' => 
  array (
    0 => 'VG',
  ),
  'America/St_Thomas' => 
  array (
    0 => 'VI',
  ),
  'Asia/Saigon' => 
  array (
    0 => 'VN',
  ),
  'Pacific/Efate' => 
  array (
    0 => 'VU',
  ),
  'Pacific/Wallis' => 
  array (
    0 => 'WF',
  ),
  'Pacific/Apia' => 
  array (
    0 => 'WS',
  ),
  'Asia/Aden' => 
  array (
    0 => 'YE',
  ),
  'Indian/Mayotte' => 
  array (
    0 => 'YT',
  ),
  'Africa/Johannesburg' => 
  array (
    0 => 'ZA',
  ),
  'Africa/Lusaka' => 
  array (
    0 => 'ZM',
  ),
  'Africa/Harare' => 
  array (
    0 => 'ZW',
  ),
);
}
?>