<?php
# !! WARNING ! WARNING ! WARNING ! WARNING ! WARNING ! WARNING !!
# !!                                                           !!
# !!   This file is autogenerated by generate.php              !!
# !!                                                           !!
# !!   DO NOT change it.  ALL changes will be lost after you   !!
# !!   regenerate it again.                                    !!
# !!                                                           !!
# !! WARNING ! WARNING ! WARNING ! WARNING ! WARNING ! WARNING !!
/**
 * Support data classes for the Simple Registration Extension.
 */
/**
 * Raw list of all Countries.
 *
 * @see OpenID_SR_Country
 * @package OpenID.SR.data
 */
class OpenID_SR_data_AutoGeneratedCountry
{
    /**
     * ISO-3166-2 Country Codes.
     *
     * This Hash is keyed by the Two Letter Country Code, and each
     * element is a Hash with a single key 'name'.
     *
     * Example:
     *
     * <code>
     * $data = array(
     *     'PT' => array('name' => 'Portugal'),
     * );
     * </code>
     *
     * @var hash
     */
    static $data = array (
  'AF' => 
  array (
    'name' => 'Afghanistan',
  ),
  'AX' => 
  array (
    'name' => 'Åland Islands',
  ),
  'AL' => 
  array (
    'name' => 'Albania',
  ),
  'DZ' => 
  array (
    'name' => 'Algeria',
  ),
  'AS' => 
  array (
    'name' => 'American Samoa',
  ),
  'AD' => 
  array (
    'name' => 'Andorra',
  ),
  'AO' => 
  array (
    'name' => 'Angola',
  ),
  'AI' => 
  array (
    'name' => 'Anguilla',
  ),
  'AQ' => 
  array (
    'name' => 'Antarctica',
  ),
  'AG' => 
  array (
    'name' => 'Antigua and Barbuda',
  ),
  'AR' => 
  array (
    'name' => 'Argentina',
  ),
  'AM' => 
  array (
    'name' => 'Armenia',
  ),
  'AW' => 
  array (
    'name' => 'Aruba',
  ),
  'AU' => 
  array (
    'name' => 'Australia',
  ),
  'AT' => 
  array (
    'name' => 'Austria',
  ),
  'AZ' => 
  array (
    'name' => 'Azerbaijan',
  ),
  'BS' => 
  array (
    'name' => 'Bahamas',
  ),
  'BH' => 
  array (
    'name' => 'Bahrain',
  ),
  'BD' => 
  array (
    'name' => 'Bangladesh',
  ),
  'BB' => 
  array (
    'name' => 'Barbados',
  ),
  'BY' => 
  array (
    'name' => 'Belarus',
  ),
  'BE' => 
  array (
    'name' => 'Belgium',
  ),
  'BZ' => 
  array (
    'name' => 'Belize',
  ),
  'BJ' => 
  array (
    'name' => 'Benin',
  ),
  'BM' => 
  array (
    'name' => 'Bermuda',
  ),
  'BT' => 
  array (
    'name' => 'Bhutan',
  ),
  'BO' => 
  array (
    'name' => 'Bolivia',
  ),
  'BA' => 
  array (
    'name' => 'Bosnia and Herzegovina',
  ),
  'BW' => 
  array (
    'name' => 'Botswana',
  ),
  'BV' => 
  array (
    'name' => 'Bouvet Island',
  ),
  'BR' => 
  array (
    'name' => 'Brazil',
  ),
  'IO' => 
  array (
    'name' => 'British Indian Ocean Territory',
  ),
  'BN' => 
  array (
    'name' => 'Brunei Darussalam',
  ),
  'BG' => 
  array (
    'name' => 'Bulgaria',
  ),
  'BF' => 
  array (
    'name' => 'Burkina Faso',
  ),
  'BI' => 
  array (
    'name' => 'Burundi',
  ),
  'KH' => 
  array (
    'name' => 'Cambodia',
  ),
  'CM' => 
  array (
    'name' => 'Cameroon',
  ),
  'CA' => 
  array (
    'name' => 'Canada',
  ),
  'CV' => 
  array (
    'name' => 'Cape Verde',
  ),
  'KY' => 
  array (
    'name' => 'Cayman Islands',
  ),
  'CF' => 
  array (
    'name' => 'Central African Republic',
  ),
  'TD' => 
  array (
    'name' => 'Chad',
  ),
  'CL' => 
  array (
    'name' => 'Chile',
  ),
  'CN' => 
  array (
    'name' => 'China',
  ),
  'CX' => 
  array (
    'name' => 'Christmas Island',
  ),
  'CC' => 
  array (
    'name' => 'Cocos (Keeling) Islands',
  ),
  'CO' => 
  array (
    'name' => 'Colombia',
  ),
  'KM' => 
  array (
    'name' => 'Comoros',
  ),
  'CG' => 
  array (
    'name' => 'Congo',
  ),
  'CD' => 
  array (
    'name' => 'Congo, The Democratic Republic of the',
  ),
  'CK' => 
  array (
    'name' => 'Cook Islands',
  ),
  'CR' => 
  array (
    'name' => 'Costa Rica',
  ),
  'CI' => 
  array (
    'name' => 'Côte d\'Ivoire',
  ),
  'HR' => 
  array (
    'name' => 'Croatia',
  ),
  'CU' => 
  array (
    'name' => 'Cuba',
  ),
  'CY' => 
  array (
    'name' => 'Cyprus',
  ),
  'CZ' => 
  array (
    'name' => 'Czech Republic',
  ),
  'DK' => 
  array (
    'name' => 'Denmark',
  ),
  'DJ' => 
  array (
    'name' => 'Djibouti',
  ),
  'DM' => 
  array (
    'name' => 'Dominica',
  ),
  'DO' => 
  array (
    'name' => 'Dominican Republic',
  ),
  'EC' => 
  array (
    'name' => 'Ecuador',
  ),
  'EG' => 
  array (
    'name' => 'Egypt',
  ),
  'SV' => 
  array (
    'name' => 'El Salvador',
  ),
  'GQ' => 
  array (
    'name' => 'Equatorial Guinea',
  ),
  'ER' => 
  array (
    'name' => 'Eritrea',
  ),
  'EE' => 
  array (
    'name' => 'Estonia',
  ),
  'ET' => 
  array (
    'name' => 'Ethiopia',
  ),
  'FK' => 
  array (
    'name' => 'Falkland Islands (Malvinas)',
  ),
  'FO' => 
  array (
    'name' => 'Faroe Islands',
  ),
  'FJ' => 
  array (
    'name' => 'Fiji',
  ),
  'FI' => 
  array (
    'name' => 'Finland',
  ),
  'FR' => 
  array (
    'name' => 'France',
  ),
  'GF' => 
  array (
    'name' => 'French Guiana',
  ),
  'PF' => 
  array (
    'name' => 'French Polynesia',
  ),
  'TF' => 
  array (
    'name' => 'French Southern Territories',
  ),
  'GA' => 
  array (
    'name' => 'Gabon',
  ),
  'GM' => 
  array (
    'name' => 'Gambia',
  ),
  'GE' => 
  array (
    'name' => 'Georgia',
  ),
  'DE' => 
  array (
    'name' => 'Germany',
  ),
  'GH' => 
  array (
    'name' => 'Ghana',
  ),
  'GI' => 
  array (
    'name' => 'Gibraltar',
  ),
  'GR' => 
  array (
    'name' => 'Greece',
  ),
  'GL' => 
  array (
    'name' => 'Greenland',
  ),
  'GD' => 
  array (
    'name' => 'Grenada',
  ),
  'GP' => 
  array (
    'name' => 'Guadeloupe',
  ),
  'GU' => 
  array (
    'name' => 'Guam',
  ),
  'GT' => 
  array (
    'name' => 'Guatemala',
  ),
  'GG' => 
  array (
    'name' => 'Guernsey',
  ),
  'GN' => 
  array (
    'name' => 'Guinea',
  ),
  'GW' => 
  array (
    'name' => 'Guinea-Bissau',
  ),
  'GY' => 
  array (
    'name' => 'Guyana',
  ),
  'HT' => 
  array (
    'name' => 'Haiti',
  ),
  'HM' => 
  array (
    'name' => 'Heard Island and McDonald Islands',
  ),
  'VA' => 
  array (
    'name' => 'Holy See (Vatican City State)',
  ),
  'HN' => 
  array (
    'name' => 'Honduras',
  ),
  'HK' => 
  array (
    'name' => 'Hong Kong',
  ),
  'HU' => 
  array (
    'name' => 'Hungary',
  ),
  'IS' => 
  array (
    'name' => 'Iceland',
  ),
  'IN' => 
  array (
    'name' => 'India',
  ),
  'ID' => 
  array (
    'name' => 'Indonesia',
  ),
  'IR' => 
  array (
    'name' => 'Iran, Islamic Republic of',
  ),
  'IQ' => 
  array (
    'name' => 'Iraq',
  ),
  'IE' => 
  array (
    'name' => 'Ireland',
  ),
  'IM' => 
  array (
    'name' => 'Isle of Man',
  ),
  'IL' => 
  array (
    'name' => 'Israel',
  ),
  'IT' => 
  array (
    'name' => 'Italy',
  ),
  'JM' => 
  array (
    'name' => 'Jamaica',
  ),
  'JP' => 
  array (
    'name' => 'Japan',
  ),
  'JE' => 
  array (
    'name' => 'Jersey',
  ),
  'JO' => 
  array (
    'name' => 'Jordan',
  ),
  'KZ' => 
  array (
    'name' => 'Kazakhstan',
  ),
  'KE' => 
  array (
    'name' => 'Kenya',
  ),
  'KI' => 
  array (
    'name' => 'Kiribati',
  ),
  'KP' => 
  array (
    'name' => 'Korea, Democratic People\'s Republic of',
  ),
  'KR' => 
  array (
    'name' => 'Korea, Republic of',
  ),
  'KW' => 
  array (
    'name' => 'Kuwait',
  ),
  'KG' => 
  array (
    'name' => 'Kyrgyzstan',
  ),
  'LA' => 
  array (
    'name' => 'Lao People\'s Democratic Republic',
  ),
  'LV' => 
  array (
    'name' => 'Latvia',
  ),
  'LB' => 
  array (
    'name' => 'Lebanon',
  ),
  'LS' => 
  array (
    'name' => 'Lesotho',
  ),
  'LR' => 
  array (
    'name' => 'Liberia',
  ),
  'LY' => 
  array (
    'name' => 'Libyan Arab Jamahiriya',
  ),
  'LI' => 
  array (
    'name' => 'Liechtenstein',
  ),
  'LT' => 
  array (
    'name' => 'Lithuania',
  ),
  'LU' => 
  array (
    'name' => 'Luxembourg',
  ),
  'MO' => 
  array (
    'name' => 'Macao',
  ),
  'MK' => 
  array (
    'name' => 'Macedonia, Republic of',
  ),
  'MG' => 
  array (
    'name' => 'Madagascar',
  ),
  'MW' => 
  array (
    'name' => 'Malawi',
  ),
  'MY' => 
  array (
    'name' => 'Malaysia',
  ),
  'MV' => 
  array (
    'name' => 'Maldives',
  ),
  'ML' => 
  array (
    'name' => 'Mali',
  ),
  'MT' => 
  array (
    'name' => 'Malta',
  ),
  'MH' => 
  array (
    'name' => 'Marshall Islands',
  ),
  'MQ' => 
  array (
    'name' => 'Martinique',
  ),
  'MR' => 
  array (
    'name' => 'Mauritania',
  ),
  'MU' => 
  array (
    'name' => 'Mauritius',
  ),
  'YT' => 
  array (
    'name' => 'Mayotte',
  ),
  'MX' => 
  array (
    'name' => 'Mexico',
  ),
  'FM' => 
  array (
    'name' => 'Micronesia, Federated States of',
  ),
  'MD' => 
  array (
    'name' => 'Moldova, Republic of',
  ),
  'MC' => 
  array (
    'name' => 'Monaco',
  ),
  'MN' => 
  array (
    'name' => 'Mongolia',
  ),
  'ME' => 
  array (
    'name' => 'Montenegro',
  ),
  'MS' => 
  array (
    'name' => 'Montserrat',
  ),
  'MA' => 
  array (
    'name' => 'Morocco',
  ),
  'MZ' => 
  array (
    'name' => 'Mozambique',
  ),
  'MM' => 
  array (
    'name' => 'Myanmar',
  ),
  'NA' => 
  array (
    'name' => 'Namibia',
  ),
  'NR' => 
  array (
    'name' => 'Nauru',
  ),
  'NP' => 
  array (
    'name' => 'Nepal',
  ),
  'NL' => 
  array (
    'name' => 'Netherlands',
  ),
  'AN' => 
  array (
    'name' => 'Netherlands Antilles',
  ),
  'NC' => 
  array (
    'name' => 'New Caledonia',
  ),
  'NZ' => 
  array (
    'name' => 'New Zealand',
  ),
  'NI' => 
  array (
    'name' => 'Nicaragua',
  ),
  'NE' => 
  array (
    'name' => 'Niger',
  ),
  'NG' => 
  array (
    'name' => 'Nigeria',
  ),
  'NU' => 
  array (
    'name' => 'Niue',
  ),
  'NF' => 
  array (
    'name' => 'Norfolk Island',
  ),
  'MP' => 
  array (
    'name' => 'Northern Mariana Islands',
  ),
  'NO' => 
  array (
    'name' => 'Norway',
  ),
  'OM' => 
  array (
    'name' => 'Oman',
  ),
  'PK' => 
  array (
    'name' => 'Pakistan',
  ),
  'PW' => 
  array (
    'name' => 'Palau',
  ),
  'PS' => 
  array (
    'name' => 'Palestinian Territory, Occupied',
  ),
  'PA' => 
  array (
    'name' => 'Panama',
  ),
  'PG' => 
  array (
    'name' => 'Papua New Guinea',
  ),
  'PY' => 
  array (
    'name' => 'Paraguay',
  ),
  'PE' => 
  array (
    'name' => 'Peru',
  ),
  'PH' => 
  array (
    'name' => 'Philippines',
  ),
  'PN' => 
  array (
    'name' => 'Pitcairn',
  ),
  'PL' => 
  array (
    'name' => 'Poland',
  ),
  'PT' => 
  array (
    'name' => 'Portugal',
  ),
  'PR' => 
  array (
    'name' => 'Puerto Rico',
  ),
  'QA' => 
  array (
    'name' => 'Qatar',
  ),
  'RE' => 
  array (
    'name' => 'Reunion',
  ),
  'RO' => 
  array (
    'name' => 'Romania',
  ),
  'RU' => 
  array (
    'name' => 'Russian Federation',
  ),
  'RW' => 
  array (
    'name' => 'Rwanda',
  ),
  'SH' => 
  array (
    'name' => 'Saint Helena',
  ),
  'KN' => 
  array (
    'name' => 'Saint Kitts and Nevis',
  ),
  'LC' => 
  array (
    'name' => 'Saint Lucia',
  ),
  'PM' => 
  array (
    'name' => 'Saint Pierre and Miquelon',
  ),
  'VC' => 
  array (
    'name' => 'Saint Vincent and the Grenadines',
  ),
  'WS' => 
  array (
    'name' => 'Samoa',
  ),
  'SM' => 
  array (
    'name' => 'San Marino',
  ),
  'ST' => 
  array (
    'name' => 'Sao Tome and Principe',
  ),
  'SA' => 
  array (
    'name' => 'Saudi Arabia',
  ),
  'SN' => 
  array (
    'name' => 'Senegal',
  ),
  'RS' => 
  array (
    'name' => 'Serbia',
  ),
  'SC' => 
  array (
    'name' => 'Seychelles',
  ),
  'SL' => 
  array (
    'name' => 'Sierra Leone',
  ),
  'SG' => 
  array (
    'name' => 'Singapore',
  ),
  'SK' => 
  array (
    'name' => 'Slovakia',
  ),
  'SI' => 
  array (
    'name' => 'Slovenia',
  ),
  'SB' => 
  array (
    'name' => 'Solomon Islands',
  ),
  'SO' => 
  array (
    'name' => 'Somalia',
  ),
  'ZA' => 
  array (
    'name' => 'South Africa',
  ),
  'GS' => 
  array (
    'name' => 'South Georgia and the South Sandwich Islands',
  ),
  'ES' => 
  array (
    'name' => 'Spain',
  ),
  'LK' => 
  array (
    'name' => 'Sri Lanka',
  ),
  'SD' => 
  array (
    'name' => 'Sudan',
  ),
  'SR' => 
  array (
    'name' => 'Suriname',
  ),
  'SJ' => 
  array (
    'name' => 'Svalbard and Jan Mayen',
  ),
  'SZ' => 
  array (
    'name' => 'Swaziland',
  ),
  'SE' => 
  array (
    'name' => 'Sweden',
  ),
  'CH' => 
  array (
    'name' => 'Switzerland',
  ),
  'SY' => 
  array (
    'name' => 'Syrian Arab Republic',
  ),
  'TW' => 
  array (
    'name' => 'Taiwan, Province of China',
  ),
  'TJ' => 
  array (
    'name' => 'Tajikistan',
  ),
  'TZ' => 
  array (
    'name' => 'Tanzania, United Republic of',
  ),
  'TH' => 
  array (
    'name' => 'Thailand',
  ),
  'TL' => 
  array (
    'name' => 'Timor-Leste',
  ),
  'TG' => 
  array (
    'name' => 'Togo',
  ),
  'TK' => 
  array (
    'name' => 'Tokelau',
  ),
  'TO' => 
  array (
    'name' => 'Tonga',
  ),
  'TT' => 
  array (
    'name' => 'Trinidad and Tobago',
  ),
  'TN' => 
  array (
    'name' => 'Tunisia',
  ),
  'TR' => 
  array (
    'name' => 'Turkey',
  ),
  'TM' => 
  array (
    'name' => 'Turkmenistan',
  ),
  'TC' => 
  array (
    'name' => 'Turks and Caicos Islands',
  ),
  'TV' => 
  array (
    'name' => 'Tuvalu',
  ),
  'UG' => 
  array (
    'name' => 'Uganda',
  ),
  'UA' => 
  array (
    'name' => 'Ukraine',
  ),
  'AE' => 
  array (
    'name' => 'United Arab Emirates',
  ),
  'GB' => 
  array (
    'name' => 'United Kingdom',
  ),
  'US' => 
  array (
    'name' => 'United States',
  ),
  'UM' => 
  array (
    'name' => 'United States Minor Outlying Islands',
  ),
  'UY' => 
  array (
    'name' => 'Uruguay',
  ),
  'UZ' => 
  array (
    'name' => 'Uzbekistan',
  ),
  'VU' => 
  array (
    'name' => 'Vanuatu',
  ),
  'VE' => 
  array (
    'name' => 'Venezuela',
  ),
  'VN' => 
  array (
    'name' => 'Viet Nam',
  ),
  'VG' => 
  array (
    'name' => 'Virgin Islands, British',
  ),
  'VI' => 
  array (
    'name' => 'Virgin Islands, U.S.',
  ),
  'WF' => 
  array (
    'name' => 'Wallis and Futuna',
  ),
  'EH' => 
  array (
    'name' => 'Western Sahara',
  ),
  'YE' => 
  array (
    'name' => 'Yemen',
  ),
  'ZM' => 
  array (
    'name' => 'Zambia',
  ),
  'ZW' => 
  array (
    'name' => 'Zimbabwe',
  ),
);
}
?>