<?php
# !! WARNING ! WARNING ! WARNING ! WARNING ! WARNING ! WARNING !!
# !!                                                           !!
# !!   This file is autogenerated by generate.php              !!
# !!                                                           !!
# !!   DO NOT change it.  ALL changes will be lost after you   !!
# !!   regenerate it again.                                    !!
# !!                                                           !!
# !! WARNING ! WARNING ! WARNING ! WARNING ! WARNING ! WARNING !!
/**
 * Support data classes for the Simple Registration Extension.
 */
/**
 * Raw list of all Languages.
 *
 * @see OpenID_SR_Language
 * @package OpenID.SR.data
 */
class OpenID_SR_data_AutoGeneratedLanguage
{
    /**
     * ISO-639-2 Language Codes.
     *
     * This Hash is keyed by the Two Letter Language Code, and each
     * element is a Hash with a single key 'name'.
     *
     * Example:
     *
     * <code>
     * $data = array(
     *     'pt' => array('name' => 'Portuguese'),
     * );
     * </code>
     *
     * @var hash
     */
    static $data = array (
  'aa' => 
  array (
    'name' => 'Afar',
  ),
  'ab' => 
  array (
    'name' => 'Abkhazian',
  ),
  'af' => 
  array (
    'name' => 'Afrikaans',
  ),
  'ak' => 
  array (
    'name' => 'Akan',
  ),
  'sq' => 
  array (
    'name' => 'Albanian',
  ),
  'am' => 
  array (
    'name' => 'Amharic',
  ),
  'ar' => 
  array (
    'name' => 'Arabic',
  ),
  'an' => 
  array (
    'name' => 'Aragonese',
  ),
  'hy' => 
  array (
    'name' => 'Armenian',
  ),
  'as' => 
  array (
    'name' => 'Assamese',
  ),
  'av' => 
  array (
    'name' => 'Avaric',
  ),
  'ae' => 
  array (
    'name' => 'Avestan',
  ),
  'ay' => 
  array (
    'name' => 'Aymara',
  ),
  'az' => 
  array (
    'name' => 'Azerbaijani',
  ),
  'ba' => 
  array (
    'name' => 'Bashkir',
  ),
  'bm' => 
  array (
    'name' => 'Bambara',
  ),
  'eu' => 
  array (
    'name' => 'Basque',
  ),
  'be' => 
  array (
    'name' => 'Belarusian',
  ),
  'bn' => 
  array (
    'name' => 'Bengali',
  ),
  'bh' => 
  array (
    'name' => 'Bihari',
  ),
  'bi' => 
  array (
    'name' => 'Bislama',
  ),
  'bs' => 
  array (
    'name' => 'Bosnian',
  ),
  'br' => 
  array (
    'name' => 'Breton',
  ),
  'bg' => 
  array (
    'name' => 'Bulgarian',
  ),
  'my' => 
  array (
    'name' => 'Burmese',
  ),
  'ca' => 
  array (
    'name' => 'Catalan; Valencian',
  ),
  'ch' => 
  array (
    'name' => 'Chamorro',
  ),
  'ce' => 
  array (
    'name' => 'Chechen',
  ),
  'zh' => 
  array (
    'name' => 'Chinese',
  ),
  'cu' => 
  array (
    'name' => 'Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic',
  ),
  'cv' => 
  array (
    'name' => 'Chuvash',
  ),
  'kw' => 
  array (
    'name' => 'Cornish',
  ),
  'co' => 
  array (
    'name' => 'Corsican',
  ),
  'cr' => 
  array (
    'name' => 'Cree',
  ),
  'cs' => 
  array (
    'name' => 'Czech',
  ),
  'da' => 
  array (
    'name' => 'Danish',
  ),
  'dv' => 
  array (
    'name' => 'Divehi; Dhivehi; Maldivian',
  ),
  'nl' => 
  array (
    'name' => 'Dutch; Flemish',
  ),
  'dz' => 
  array (
    'name' => 'Dzongkha',
  ),
  'en' => 
  array (
    'name' => 'English',
  ),
  'eo' => 
  array (
    'name' => 'Esperanto',
  ),
  'et' => 
  array (
    'name' => 'Estonian',
  ),
  'ee' => 
  array (
    'name' => 'Ewe',
  ),
  'fo' => 
  array (
    'name' => 'Faroese',
  ),
  'fj' => 
  array (
    'name' => 'Fijian',
  ),
  'fi' => 
  array (
    'name' => 'Finnish',
  ),
  'fr' => 
  array (
    'name' => 'French',
  ),
  'fy' => 
  array (
    'name' => 'Western Frisian',
  ),
  'ff' => 
  array (
    'name' => 'Fulah',
  ),
  'ka' => 
  array (
    'name' => 'Georgian',
  ),
  'de' => 
  array (
    'name' => 'German',
  ),
  'gd' => 
  array (
    'name' => 'Gaelic; Scottish Gaelic',
  ),
  'ga' => 
  array (
    'name' => 'Irish',
  ),
  'gl' => 
  array (
    'name' => 'Galician',
  ),
  'gv' => 
  array (
    'name' => 'Manx',
  ),
  'el' => 
  array (
    'name' => 'Greek, Modern (1453-)',
  ),
  'gn' => 
  array (
    'name' => 'Guarani',
  ),
  'gu' => 
  array (
    'name' => 'Gujarati',
  ),
  'ht' => 
  array (
    'name' => 'Haitian; Haitian Creole',
  ),
  'ha' => 
  array (
    'name' => 'Hausa',
  ),
  'he' => 
  array (
    'name' => 'Hebrew',
  ),
  'hz' => 
  array (
    'name' => 'Herero',
  ),
  'hi' => 
  array (
    'name' => 'Hindi',
  ),
  'ho' => 
  array (
    'name' => 'Hiri Motu',
  ),
  'hu' => 
  array (
    'name' => 'Hungarian',
  ),
  'ig' => 
  array (
    'name' => 'Igbo',
  ),
  'is' => 
  array (
    'name' => 'Icelandic',
  ),
  'io' => 
  array (
    'name' => 'Ido',
  ),
  'ii' => 
  array (
    'name' => 'Sichuan Yi',
  ),
  'iu' => 
  array (
    'name' => 'Inuktitut',
  ),
  'ie' => 
  array (
    'name' => 'Interlingue',
  ),
  'ia' => 
  array (
    'name' => 'Interlingua (International Auxiliary Language Association)',
  ),
  'id' => 
  array (
    'name' => 'Indonesian',
  ),
  'ik' => 
  array (
    'name' => 'Inupiaq',
  ),
  'it' => 
  array (
    'name' => 'Italian',
  ),
  'jv' => 
  array (
    'name' => 'Javanese',
  ),
  'ja' => 
  array (
    'name' => 'Japanese',
  ),
  'kl' => 
  array (
    'name' => 'Kalaallisut; Greenlandic',
  ),
  'kn' => 
  array (
    'name' => 'Kannada',
  ),
  'ks' => 
  array (
    'name' => 'Kashmiri',
  ),
  'kr' => 
  array (
    'name' => 'Kanuri',
  ),
  'kk' => 
  array (
    'name' => 'Kazakh',
  ),
  'km' => 
  array (
    'name' => 'Central Khmer',
  ),
  'ki' => 
  array (
    'name' => 'Kikuyu; Gikuyu',
  ),
  'rw' => 
  array (
    'name' => 'Kinyarwanda',
  ),
  'ky' => 
  array (
    'name' => 'Kirghiz; Kyrgyz',
  ),
  'kv' => 
  array (
    'name' => 'Komi',
  ),
  'kg' => 
  array (
    'name' => 'Kongo',
  ),
  'ko' => 
  array (
    'name' => 'Korean',
  ),
  'kj' => 
  array (
    'name' => 'Kuanyama; Kwanyama',
  ),
  'ku' => 
  array (
    'name' => 'Kurdish',
  ),
  'lo' => 
  array (
    'name' => 'Lao',
  ),
  'la' => 
  array (
    'name' => 'Latin',
  ),
  'lv' => 
  array (
    'name' => 'Latvian',
  ),
  'li' => 
  array (
    'name' => 'Limburgan; Limburger; Limburgish',
  ),
  'ln' => 
  array (
    'name' => 'Lingala',
  ),
  'lt' => 
  array (
    'name' => 'Lithuanian',
  ),
  'lb' => 
  array (
    'name' => 'Luxembourgish; Letzeburgesch',
  ),
  'lu' => 
  array (
    'name' => 'Luba-Katanga',
  ),
  'lg' => 
  array (
    'name' => 'Ganda',
  ),
  'mk' => 
  array (
    'name' => 'Macedonian',
  ),
  'mh' => 
  array (
    'name' => 'Marshallese',
  ),
  'ml' => 
  array (
    'name' => 'Malayalam',
  ),
  'mi' => 
  array (
    'name' => 'Maori',
  ),
  'mr' => 
  array (
    'name' => 'Marathi',
  ),
  'ms' => 
  array (
    'name' => 'Malay',
  ),
  'mg' => 
  array (
    'name' => 'Malagasy',
  ),
  'mt' => 
  array (
    'name' => 'Maltese',
  ),
  'mo' => 
  array (
    'name' => 'Moldavian',
  ),
  'mn' => 
  array (
    'name' => 'Mongolian',
  ),
  'na' => 
  array (
    'name' => 'Nauru',
  ),
  'nv' => 
  array (
    'name' => 'Navajo; Navaho',
  ),
  'nr' => 
  array (
    'name' => 'Ndebele, South; South Ndebele',
  ),
  'nd' => 
  array (
    'name' => 'Ndebele, North; North Ndebele',
  ),
  'ng' => 
  array (
    'name' => 'Ndonga',
  ),
  'ne' => 
  array (
    'name' => 'Nepali',
  ),
  'nn' => 
  array (
    'name' => 'Norwegian Nynorsk; Nynorsk, Norwegian',
  ),
  'nb' => 
  array (
    'name' => 'Norwegian Bokmål; Bokmål, Norwegian',
  ),
  'no' => 
  array (
    'name' => 'Norwegian',
  ),
  'ny' => 
  array (
    'name' => 'Chichewa; Chewa; Nyanja',
  ),
  'oc' => 
  array (
    'name' => 'Occitan (post 1500); Provençal',
  ),
  'oj' => 
  array (
    'name' => 'Ojibwa',
  ),
  'or' => 
  array (
    'name' => 'Oriya',
  ),
  'om' => 
  array (
    'name' => 'Oromo',
  ),
  'os' => 
  array (
    'name' => 'Ossetian; Ossetic',
  ),
  'pa' => 
  array (
    'name' => 'Panjabi; Punjabi',
  ),
  'fa' => 
  array (
    'name' => 'Persian',
  ),
  'pi' => 
  array (
    'name' => 'Pali',
  ),
  'pl' => 
  array (
    'name' => 'Polish',
  ),
  'pt' => 
  array (
    'name' => 'Portuguese',
  ),
  'ps' => 
  array (
    'name' => 'Pushto',
  ),
  'qu' => 
  array (
    'name' => 'Quechua',
  ),
  'rm' => 
  array (
    'name' => 'Romansh',
  ),
  'ro' => 
  array (
    'name' => 'Romanian',
  ),
  'rn' => 
  array (
    'name' => 'Rundi',
  ),
  'ru' => 
  array (
    'name' => 'Russian',
  ),
  'sg' => 
  array (
    'name' => 'Sango',
  ),
  'sa' => 
  array (
    'name' => 'Sanskrit',
  ),
  'sr' => 
  array (
    'name' => 'Serbian',
  ),
  'hr' => 
  array (
    'name' => 'Croatian',
  ),
  'si' => 
  array (
    'name' => 'Sinhala; Sinhalese',
  ),
  'sk' => 
  array (
    'name' => 'Slovak',
  ),
  'sl' => 
  array (
    'name' => 'Slovenian',
  ),
  'se' => 
  array (
    'name' => 'Northern Sami',
  ),
  'sm' => 
  array (
    'name' => 'Samoan',
  ),
  'sn' => 
  array (
    'name' => 'Shona',
  ),
  'sd' => 
  array (
    'name' => 'Sindhi',
  ),
  'so' => 
  array (
    'name' => 'Somali',
  ),
  'st' => 
  array (
    'name' => 'Sotho, Southern',
  ),
  'es' => 
  array (
    'name' => 'Spanish; Castilian',
  ),
  'sc' => 
  array (
    'name' => 'Sardinian',
  ),
  'ss' => 
  array (
    'name' => 'Swati',
  ),
  'su' => 
  array (
    'name' => 'Sundanese',
  ),
  'sw' => 
  array (
    'name' => 'Swahili',
  ),
  'sv' => 
  array (
    'name' => 'Swedish',
  ),
  'ty' => 
  array (
    'name' => 'Tahitian',
  ),
  'ta' => 
  array (
    'name' => 'Tamil',
  ),
  'tt' => 
  array (
    'name' => 'Tatar',
  ),
  'te' => 
  array (
    'name' => 'Telugu',
  ),
  'tg' => 
  array (
    'name' => 'Tajik',
  ),
  'tl' => 
  array (
    'name' => 'Tagalog',
  ),
  'th' => 
  array (
    'name' => 'Thai',
  ),
  'bo' => 
  array (
    'name' => 'Tibetan',
  ),
  'ti' => 
  array (
    'name' => 'Tigrinya',
  ),
  'to' => 
  array (
    'name' => 'Tonga (Tonga Islands)',
  ),
  'tn' => 
  array (
    'name' => 'Tswana',
  ),
  'ts' => 
  array (
    'name' => 'Tsonga',
  ),
  'tk' => 
  array (
    'name' => 'Turkmen',
  ),
  'tr' => 
  array (
    'name' => 'Turkish',
  ),
  'tw' => 
  array (
    'name' => 'Twi',
  ),
  'ug' => 
  array (
    'name' => 'Uighur; Uyghur',
  ),
  'uk' => 
  array (
    'name' => 'Ukrainian',
  ),
  'ur' => 
  array (
    'name' => 'Urdu',
  ),
  'uz' => 
  array (
    'name' => 'Uzbek',
  ),
  've' => 
  array (
    'name' => 'Venda',
  ),
  'vi' => 
  array (
    'name' => 'Vietnamese',
  ),
  'vo' => 
  array (
    'name' => 'Volapük',
  ),
  'cy' => 
  array (
    'name' => 'Welsh',
  ),
  'wa' => 
  array (
    'name' => 'Walloon',
  ),
  'wo' => 
  array (
    'name' => 'Wolof',
  ),
  'xh' => 
  array (
    'name' => 'Xhosa',
  ),
  'yi' => 
  array (
    'name' => 'Yiddish',
  ),
  'yo' => 
  array (
    'name' => 'Yoruba',
  ),
  'za' => 
  array (
    'name' => 'Zhuang; Chuang',
  ),
  'zu' => 
  array (
    'name' => 'Zulu',
  ),
);
}
?>