<?php
/**
 * Simple Registration support classes.
 *
 * @package OpenID.SR
 */
/**
 * Represents a Simple Registration Language.
 *
 * A country in OpenID is represented using the two leter code from ISO639.
 *
 * @link http://packages.debian.org/cgi-bin/search_packages.pl?searchon=names&version=all&exact=1&keywords=iso-codes iso-codes package 
 *
 * @package OpenID.SR
 */
class OpenID_SR_Language
{
    private static $data;
    private $code;
    private $name;

    private function __construct($code, $name)
    {
        $this->code = $code;
        $this->name = $name;
    }

    /** @return string this language code */
    public function code()
    {
        return $this->code;
    }

    /** @return string this language code */
    public function name()
    {
        return $this->name;
    }

    /**
     * Returns the language that has the given code.
     *
     * @param string $code the language code to find
     * @return OpenID_SR_Language
     */
    public static function fromCode($code)
    {
        OpenID_SR_Language::load();
        if (!array_key_exists($code, OpenID_SR_Language::$data))
    	   return null;
        $entry = OpenID_SR_Language::$data[$code];
        return new OpenID_SR_Language($code, $entry['name']);
    }

    /** @return array array of OpenID_SR_Language with all the languages */
    public static function all()
    {
        OpenID_SR_Language::load();
        $all = array();
        foreach (OpenID_SR_Language::$data as $code => $keys) {
            $all[] = new OpenID_SR_Language($code, $keys['name']);
        }
        return $all;
    }

    private static function load()
    {
        if (OpenID_SR_Language::$data)
            return;
        require_once('OpenID/SR/data/AutoGeneratedLanguage.php');
        OpenID_SR_Language::$data = OpenID_SR_data_AutoGeneratedLanguage::$data;
    }
}
?>
