<?php
/**
 * Simple Registration support classes.
 *
 * @package OpenID.SR
 */
/**
 * Represents a Simple Registration Time Zone.
 *
 * A TimeZone in OpenID is represented using the TZ code from the Tz Data.
 *
 * @link http://www.twinsun.com/tz/tz-link.htm  Time Zone and Daylight Saving Time Data
 * @package OpenID.SR
 */
class OpenID_SR_TimeZone
{
    private static $data;
    private static $zoneToCountry;
    private $code;

    private function __construct($code)
    {
        $this->code = $code;
    }

    /** @return string this time zone code */
    public function code()
    {
        return $this->code;
    }

    /** @return string this time zone name */
    public function name()
    {
        return $this->code;
    }

    /** @return the timezone associated with the code. */
    public static function fromCode($code)
    {
        OpenID_SR_TimeZone::load();
        if (!array_key_exists($code, OpenID_SR_TimeZone::$zoneToCountry))
           return null;
        return new OpenID_SR_TimeZone($code);
    }

    /**
     * @param OpenID_SR_Country $country the country
     * @return array array of OpenID_SR_TimeZone with all timezones associated with a country
     */
    public static function fromCountry($country)
    {
        $countryCode = $country->code();
        OpenID_SR_TimeZone::load();
        if (!array_key_exists($countryCode, OpenID_SR_TimeZone::$data))
           return null;
        $entries = OpenID_SR_TimeZone::$data[$countryCode];
        $result = array();
        foreach ($entries as $entry) {
        	$tz = new OpenID_SR_TimeZone($entry['TZ']);
            $result[] = $tz;
        }
        return $result;
    }

    /** @return array array of OpenID_SR_TimeZone with all the timezones */
    public static function all()
    {
        OpenID_SR_TimeZone::load();
        $all = array();
        foreach (OpenID_SR_TimeZone::$zoneToCountry as $code => $keys) {
            $all[] = new OpenID_SR_TimeZone($code);
        }
        return $all;
    }

    private static function load()
    {
        if (OpenID_SR_TimeZone::$data)
            return;
        require_once('OpenID/SR/data/AutoGeneratedTimeZone.php');
        OpenID_SR_TimeZone::$data = OpenID_SR_data_AutoGeneratedTimeZone::$data;
        OpenID_SR_TimeZone::$zoneToCountry = OpenID_SR_data_AutoGeneratedTimeZone::$zoneToCountry;
    }
}
?>
